### ISSUE TITLE
FTP server cause crash

### ISSUE THREAD

**Issue by patrickpollet1966** [loboris/MicroPython_ESP32_psRAM_LoBo#10]
Hello,

I tried to transfer file with ftp server, in fact it never works, at best everything seems ok but the file is not written on the flash, but often i have this crash :

_______________________________________________________________
>>> uftpserver.ftpserver()
Starting ftp server. Version 1.2
FTPServer IP address:  192.168.1.13
FTP connection from: ('192.168.1.35', 62926)
Command: [USER], Payload: [micro]
Command: [CWD], Payload: [/flash]
Command: [TYPE], Payload: [A]
Command: [PASV], Payload: []
Sending: 227 Entering Passive Mode (192,168,1,13,4,26).

Command: [STOR], Payload: [init.py]
Socket accepted
OK finished.....
Guru Meditation Error: Core  0 panic'ed (Cache disabled but cached memory region accessed)
Register dump:
PC      : 0x4008565c  PS      : 0x00060034  A0      : 0x800814d2  A1      : 0x3ffaeac0  
A2      : 0x3ffbbce9  A3      : 0x00000000  A4      : 0x3ffae5cc  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x00000000  A9      : 0x3ffaeaa0  
A10     : 0x00004820  A11     : 0x3ffbbcf0  A12     : 0x00000006  A13     : 0x3ff00040  
A14     : 0x00004828  A15     : 0x00000002  SAR     : 0x00000000  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x4008565c:0x3ffaeac0 0x400814d2:0x3ffaeae0

CPU halted.

_______________________________________________________________________

Regards.

Patrick

**Comment by straga** [comment]
#5 it same problem.
Now i am tested with psram esp32-wrover-v4  thread and ftp it is works without halted.
But if get module without psram and build/flash. CPU halted, if use threads.

**Comment by straga** [comment]
One more. 
Connect to board with ./Build.sh monitor
start FTP in esp32-wrover-v4 in thread. Connect to FTP. After that repl in monitor freeze. But FTP works.

**Comment by loboris** [comment]
Today the new update will be pushed which includes FTP server implemented in C as ESP32 task (runs in background, same as telnet server). Tested for couple of days and works without issues.

**Comment by loboris** [comment]
The new implementation of the FTP server is now pushed to the repository. There is no need to use the python-implemented uftpserver (But I'll check the issues anyway...).
Please, check the [basic documentation](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/docs//servers.md)
