### ISSUE TITLE
AP  mode webserver problem solved

### ISSUE THREAD

**Issue by elektrobil** [loboris/MicroPython_ESP32_psRAM_LoBo#102]
Hi @loboris  and all sorry for my poor english
I'm using ESP32WROVER Wifi AP mode  and Lan8720. I solved this problem changed the `MicroPython_BUILD/components/micropython/esp32/modules/microWebSrv.py` 
And I add some code like this
def Start(self, threaded=True) :
        if not self._started :
            if not network.WLAN().isconnected():
                if not network.WLAN(network.AP_IF).isconnected():
                    if not network.LAN(network.PHY_LAN8720).isconnected():
                        print("Connection not ")
                        return
            gc.collect()

After added  code and build the firmware and flash the Esp32 Its work like this but a client must connect the esp32 AP before start the web server. I think boris commit this issue truly but its work for my main.py

**Comment by loboris** [comment]
Thanks, I will update microWebSrv soon (probably next week).
