### ISSUE TITLE
ftp not removing folders

### ISSUE THREAD

**Issue by kevinkk525** [loboris/MicroPython_ESP32_psRAM_LoBo#103]
Now that I can synchronize folders I recognized, that I'm unable to delete any folder.

Is this a bug or just not completely implemented?

**Comment by loboris** [comment]
Ive tested with FileZilla and it removes the folders.

It is up to the ftp client to first remove all the files in the directory, and thed remove the (now empty) directory itself.

**Comment by kevinkk525** [comment]
ok, I didn't know that the client is responsible for that. I also use filezilla as described in your wiki but the folders are not removed. 
Is it something with the filesystem on the µC?

**Comment by loboris** [comment]
Yu were right, there was a bug in ftp server causing directories not to be removed, sorry.
It is fixed now and commited.

Thanks for reporting the issue.

**Comment by kevinkk525** [comment]
Can confirm that it is fixed. Thanks a lot. Only weird things I still got is that some folders can't get deleted, not even by os.rmdir..
