### ISSUE TITLE
Port.value() gives always 0

### ISSUE THREAD

**Issue by elektrobil** [loboris/MicroPython_ESP32_psRAM_LoBo#105]
Hi @loboris
I think its a bug for new commit I wrote this code but its output always 0 or is it change usage pinout ?
`>>>pin = Pin(14,Pin.OUT)`
`>>>pin.value(1)`
`>>>pin.value()`
`0`

**Comment by loboris** [comment]
All gpio directions are now supported and follows the ESP32 names:
`machine.Pin.OUT`  **output only** (you can't read the value back)
`machine.Pin.INOUT`  input&output (that was the previous `machine.Pin.OUT`, you can read the value back)
`machine.Pin.OUT_OD` output only, open drain
`machine.Pin.INOUT_OD` input&output, open drain

Also, all the pull values for input pins are supported:
`machine.Pin.UP`
`machine.Pin.DOWN`
`machine.Pin.UPDOWN`
`machine.Pin.FLOAT`

The documentation will be updated soon.

**Comment by elektrobil** [comment]
Thank you so much. It works.
