### ISSUE TITLE
bug in pull up/down pins 34-39 safety check

### ISSUE THREAD

**Issue by visualecho1** [loboris/MicroPython_ESP32_psRAM_LoBo#11]
I think I found a bug.

In MicroPython_BUILD/components/micropython/esp32/machine_pin.c , maybe line 167:
        if ((self->id >= 34) || (self->id <= 39)) {
needs to change to:
        if ((self->id >= 34) && (self->id <= 39)) {

Thank you!

**Comment by loboris** [comment]
Thank you for reporting the bug. The fix will be pushed totay.
It is actualy enough to test _(self->id >= 34)_ as the pin number cannot be >39.
