### ISSUE TITLE
network.ftp - not work in moboXterm

### ISSUE THREAD

**Issue by straga** [loboris/MicroPython_ESP32_psRAM_LoBo#12]
Can connect. passive mode.
List put remove not working.

**Comment by straga** [comment]
For example works in thread https://github.com/robert-hh/ESP8266-FTP-Server/ftp.py

**Comment by loboris** [comment]
See the notes about FTP server limitations on [Wiki page](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/ftpserver).

It was tested on Windows with FileZilla and TotalCommander FTP plugin and works well.
No problems were detected with Linux clients.

I'll try to see what is the problem with mobaXterm when I find some time, at the moment I can only recommend to use some other FTP client.

**Comment by straga** [comment]
It same in Pycharm. 
Like many time ago in second repo it work same: not work. Open folder again and again. 
[Video FTP](https://youtu.be/HT4Lggs5bk0)

**Comment by loboris** [comment]
At he moment, you should use supported ftp clients.
I'll try to test with other ftp clients and make it work at some later time.

**Comment by loboris** [comment]
Ftp server is now updated.
Tested and works with **MobaXterm**.
It should work also with **Pycharm**, but I haven't tested it.

**Comment by straga** [comment]
Cool. I will test later. Thanks
