### ISSUE TITLE
FTP issue

### ISSUE THREAD

**Issue by slzatz** [loboris/MicroPython_ESP32_psRAM_LoBo#121]
I have been using the code below for a while, basically copied from Boris' main.py.  With the latest build I am getting:

`E (4944) [FTP] Invalid WiFi mode`

My main.py code is:

    import network
    import utime
    from settings import ssid, pw

    sta_if = network.WLAN(network.STA_IF)

    _ = sta_if.active(True)
    _ = sta_if.connect(ssid, pw)

     tmo = 50
    while not sta_if.isconnected():
        utime.sleep_ms(100)
        tmo -= 1
        if tmo == 0:
            break

    if tmo > 0:
        ifcfg = sta_if.ifconfig()
        print("WiFi started, IP:", ifcfg[0])
        utime.sleep_ms(500)

        if tmo > 0:
            utime.sleep_ms(200)
            print("Time set:", utime.strftime("%c"))
            print("")
            _ = network.ftp.start()
            _ = network.telnet.start()`

I am also having trouble with telneting into the device but not getting an error message from the telnet line above.  WiFi is actually working and I am able to use services like mqtt without a problem.  I have done a fresh clone and the problem persists.

**Comment by elektrobil** [comment]
Hi Boris
I have the same issue but Can you add PHY_LAN8720 connections too when you fix that bug ?
P.S.: I tried also AP mode and  STA mode still same error.
`Waiting LAN Active...`
`E (12191) wifi: esp_wifi_get_mode 790 wifi is not init`
`E (12192) [Ftp]: Invalid WiFi mode`

**Comment by PiAir** [comment]
I have the same issue using the FTP example code on the latest build. on a TTGO board. Can't get the current mode because WLAN object apparently has no 'mode' attribute in this build?
![wlan_no_mode](https://user-images.githubusercontent.com/6312025/38467534-460417a8-3b3a-11e8-9d60-1b8121a48cb3.JPG)

**Comment by PiAir** [comment]
I managed to get the ftp server to start by explicitly disabling the access-point interface.
![ftp_fix](https://user-images.githubusercontent.com/6312025/38468229-6e01b054-3b43-11e8-80cd-53bde458356b.JPG)

**Comment by loboris** [comment]
Some changes to `network` module are commited.

Please test and report if you still have the issues.

@PiAir 
`wlan = network.WLAN()` is eqivalent to `wlan = network.WLAN(network.STA_IF)` (Station mode is used as default).
`mode()` method is not implemented. It is suposed that you will know in which mode you have started the WiFi interface.

**Comment by slzatz** [comment]
Just updated.  Still having same issue with WiFi working but both telnet and ftp produce `Connection Refused`.  Really odd if you're not experiencing it and some people are and others are not.

**Comment by loboris** [comment]
Can you build the firmware with DEBUG log level and post the log output when initializing WiFi and starting the ftp ?

**Comment by slzatz** [comment]
Here is the main script:

    import machine
    import network
    import utime
    from settings import ssid, pw

    print("")
   print("Starting WiFi ...")

    sta_if = network.WLAN(network.STA_IF)

    _ = sta_if.active(True)
    _ = sta_if.connect(ssid, pw)

    tmo = 50
    while not sta_if.isconnected():
        utime.sleep_ms(100)
        tmo -= 1
        if tmo == 0:
            break

    if tmo > 0:
        ifcfg = sta_if.ifconfig()
        print("WiFi started, IP:", ifcfg[0])
        utime.sleep_ms(500)

        rtc = machine.RTC()
        print("Synchronize time from NTP server ...")
        rtc.ntp_sync(server="hr.pool.ntp.org", tz="EST5EDT") # update once
        #rtc.ntp_sync(server="hr.pool.ntp.org", update_period=3600)
        tmo = 100
        while not rtc.synced():
            utime.sleep_ms(100)
            tmo -= 1
            if tmo == 0:
                break

        if tmo > 0:
            utime.sleep_ms(200)
            print("Time set:", utime.strftime("%c"))
            print("start ftp and telnet")
            _ = network.ftp.start()
            _ = network.telnet.start()
            try:
                mdns = network.mDNS()
                _ = mdns.start("mPy","MicroPython with mDNS")
                _ = mdns.addService('_ftp', '_tcp', 21, "MicroPython", {"board": "ESP32", "service": "mPy FTP File transfer", "passive": "True"})
                _ = mdns.addService('_telnet', '_tcp', 23, "MicroPython", {"board": "ESP32", "service": "mPy Telnet REPL"})
                _ = mdns.addService('_http', '_tcp', 80, "MicroPython", {"board": "ESP32", "service": "mPy Web server"})
            except:
                print("mDNS not available")
`

---------------------------------------------------------------------------------------------------

And here is the log.  There is no debug info being generated when telnet and ftp are started:

     MicroPython ESP32_LoBo_v3.2.5 - 2018-04-08 on ESP32 board with ESP32
    Type "help()" for more information.
     >>> 
     >>> import machine
     >>> machine.reset()
     ets Jun  8 2016 00:22:57

     rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
     configsip: 0, SPIWP:0xee
     clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
     mode:DIO, clock div:2
     load:0x3fff0018,len:4
     load:0x3fff001c,len:4692
     load:0x40078000,len:0
     load:0x40078000,len:13268
     entry 0x40078d74
     I (593) spiram: SPI RAM mode: flash 40m sram 40m
     I (593) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
     I (595) cpu_start: Pro cpu up.
     I (598) cpu_start: Starting app cpu, entry point is 0x40081654
     I (591) cpu_start: App cpu up.
     I (1498) spiram: SPI SRAM memory test OK
     I (1499) heap_init: Initializing. RAM available for dynamic allocation:
     D (1499) heap_init: New heap initialised at 0x3ffae6e0
     I (1504) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
     D (1510) heap_init: New heap initialised at 0x3ffc1cb0
     I (1515) heap_init: At 3FFC1CB0 len 0001E350 (120 KiB): DRAM
     I (1522) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
     I (1528) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
     D (1535) heap_init: New heap initialised at 0x4009b4c0
     I (1540) heap_init: At 4009B4C0 len 00004B40 (18 KiB): IRAM
     I (1546) cpu_start: Pro cpu start user code
     I (1551) spiram: Adding pool of 4096K of external SPI memory to heap allocator
     D (1566) clk: RTC_SLOW_CLK calibration value: 3247386
     I (11) cpu_start: Starting scheduler on PRO CPU.
     I (0) cpu_start: Starting scheduler on APP CPU.
     D (13) heap_init: New heap initialised at 0x3ffe0440
     D (17) heap_init: New heap initialised at 0x3ffe4350
     I (22) MicroPython: [=== Started ===]

     Internal FS (SPIFFS): Mounted on partition 'internalfs' [size: 2555904; Flash address: 0x190000]
     ----------------
     Filesystem size: 2341888 B
           Used: 3840 B
           Free: 2338048 B
     ----------------

     Starting WiFi ...
     I (713) phy: phy_version: 383.0, 79a622c, Jan 30 2018, 15:38:06, 0, 0
     WiFi started, IP: 192.168.86.187
     Synchronize time from NTP server ...
     Time set: Sun Apr  8 16:15:23 2018
     start ftp and telnet

     FreeRTOS running on BOTH CORES, MicroPython task started on App Core.
     Running from Factory partition starting at 0x10000, [MicroPython].

      Reset reason: Soft CPU reset
         uPY stack: 19456 bytes
          uPY heap: 512256/8592/503664 bytes (in SPIRAM using heap_caps_malloc)

MicroPython ESP32_LoBo_v3.2.5 - 2018-04-08 on ESP32 board with ESP32
Type "help()" for more information.

**Comment by loboris** [comment]
It looks like you did not set `→ MicroPython → System settings → Set ESP32 log level` to DEBUG level.

Setting `→ MicroPython → System settings → FTP Server Configuration → Set FTP Server log level` to DEBUG may also give more information.

**Comment by slzatz** [comment]
OK. Sorry about that.  I set both the ESP log level to DEBUG and the FTP log level to DEBUG
and got this output:

    start ftp and telnet
    D (4304) [Ftp_start]: WiFi mode: STA
    I (4304) [Ftp]: user: micro; pass: python; buffer: 1024; timeout: 300000

    D (4309) [Telnet_start]: WiFi mode: STA
    I (4312) [Telnet]: user: micro; pass: python; timeout: 300000

To make things as confusing as possible, with those log levels set to DEBUG, both telnet and ftp now work normally.  Later today, I can turn down the log levels and see if the problem occurs again.

**Comment by slzatz** [comment]
Given that things were working with log level set to DEBUG, not sure the FTP log will be very helpful but here it is anyway for logging in and listing directory contents:

    I (437255) [Ftp]: Connected.
    D (437256) [Ftp]: Send reply: [220 Micropython FTP Server
    ]
    D (437259) [Ftp]: Send reply: OK (28)
    D (437267) [Ftp]: CMD: FEAT
    D (437267) [Ftp]: Send reply: [502 no-features
    ]
    D (437270) [Ftp]: Send reply: OK (17)
    D (437285) [Ftp]: CMD: AUTH
    D (437286) [Ftp]: Send reply: [504 not-supported
    ]
    D (437289) [Ftp]: Send reply: OK (19)
    D (437299) [Ftp]: CMD: USER
    D (437300) [Ftp]: Send reply: [331 
    ]
    D (437303) [Ftp]: Send reply: OK (6)
    D (437312) [Ftp]: CMD: PASS
    D (437312) [Ftp]: Send reply: [230 
    ]
    D (437315) [Ftp]: Send reply: OK (6)
    D (437320) [Ftp]: CMD: PWD
    D (437320) [Ftp]: Send reply: [257 /
    ]
    D (437324) [Ftp]: Send reply: OK (7)
    D (437347) [Ftp]: CMD: PASV
    D (437349) [Ftp]: Data socket created
    D (437349) [Ftp]: Send reply: [227 (192,168,86,187,7,232)
    ]
    D (437353) [Ftp]: Send reply: OK (28)
    D (437380) [Ftp]: Data socket connected
    D (437383) [Ftp]: CMD: LIST
    D (437383) [Ftp]: open_child: / + 
    D (437383) [Ftp]: open_child, New pwd: /
    D (437384) [Ftp]: ftp_open_dir_for_listing: root
    D (437389) [Ftp]: Send reply: [150 
    ]
    D (437395) [Ftp]: Send reply: OK (6)
    D (437396) [Ftp]: remove_fname_from_path: / - 
    D (437402) [Ftp]: Send list data: (55)
    D (437407) [Ftp]: Send OK
    D (437408) [Ftp]: Send reply: [226 
    ]
    D (437413) [Ftp]: Send reply: OK (6)
    D (437416) [Ftp]: Data socket disconnected
    D (617736) [Ftp]: CMD: QUIT
    D (617736) [Ftp]: Send reply: [221 
    ]
    D (617742) [Ftp]: Send reply: OK (6)
    I (683631) [Ftp]: Connected.
    D (683632) [Ftp]: Send reply: [220 Micropython FTP Server
    ]
    D (683635) [Ftp]: Send reply: OK (28)
    D (683827) [Ftp]: CMD: FEAT
    D (683828) [Ftp]: Send reply: [502 no-features
    ]
    D (683831) [Ftp]: Send reply: OK (17)
    D (684035) [Ftp]: CMD: AUTH
    D (684035) [Ftp]: Send reply: [504 not-supported
    ]
    D (684038) [Ftp]: Send reply: OK (19)
    D (684237) [Ftp]: CMD: USER
    D (684237) [Ftp]: Send reply: [331 
    ]
    D (684240) [Ftp]: Send reply: OK (6)
    D (684448) [Ftp]: CMD: PASS
    D (684448) [Ftp]: Send reply: [230     
    ]
    D (684452) [Ftp]: Send reply: OK (6)
    D (684645) [Ftp]: CMD: PWD
    D (684646) [Ftp]: Send reply: [257 /
    ]
    D (684649) [Ftp]: Send reply: OK (7)
    D (684852) [Ftp]: CMD: CWD
    D (684852) [Ftp]: open_child: / + /flash
    D (684853) [Ftp]: open_child, New pwd: /_#!#_spiffs/
    D (684853) [Ftp]: Send reply: [250 
    ]
    D (684860) [Ftp]: Send reply: OK (6)
    D (687311) [Ftp]: CMD: PASV
    D (687313) [Ftp]: Data socket created
    D (687314) [Ftp]: Send reply: [227 (192,168,86,187,7,232)
    ]
    D (687317) [Ftp]: Send reply: OK (28)
    D (687330) [Ftp]: Data socket connected
    D (687332) [Ftp]: CMD: LIST
    D (687332) [Ftp]: open_child: /_#!#_spiffs/ + 
    D (687332) [Ftp]: open_child, New pwd: /_#!#_spiffs/
    D (687335) [Ftp]: ftp_open_dir_for_listing: /_#!#_spiffs/
    D (687341) [Ftp]: Send reply: [150 
    ]
    D (687347) [Ftp]: Send reply: OK (6)
    D (687348) [Ftp]: remove_fname_from_path: /_#!#_spiffs/ - 
    D (687401) [Ftp]: Add to dir list: boot.py
    D (687402) [Ftp]: Add to dir list: main.py
    D (687403) [Ftp]: Add to dir list: settings.py
    D (687440) [Ftp]: Send list data: (175)
    D (687443) [Ftp]: Send OK
    D (687444) [Ftp]: Send reply: [226 
    ]
    D (687447) [Ftp]: Send reply: OK (6)
    D (687450) [Ftp]: Data socket disconnected

**Comment by slzatz** [comment]
Log level NONE also works fine -- what's the default log level?

**Comment by slzatz** [comment]
So assuming the normal log levels are WARNING for the system and ERROR for ftp, when I set those log levels, the problem reappears and neither ftp nor telnet works and I get CONNECTION REFUSED again.  Would certainly explain why some people are reporting the problem and others are not.  Beyond my pay scale to figure out how those specific log levels are affecting the behavior of ftp and telnet.

**Comment by loboris** [comment]
This is quite weird.
I suspect it has to have something with latest changes in esp-idf.
At least I have some starting point to start investigating. Thanks for the information.

**Comment by elektrobil** [comment]
I pulled new version and upload the flash no error occurred but filezilla gives that error:
```
Connection attempt failed with "ECONNREFUSED - Connection refused by server". 
Error:	Could not connect to server
```

**Comment by loboris** [comment]
@elektrobil 
that means the ftp server is not started, you can check with `network.ftp.status()` and you can try to start it with `network.ftp.start()`

I'm still trying to reproduce this. I've tried all combinations of log levels, but I was unsuccessful in trying **not to start** ftp server.

**Comment by loboris** [comment]
Is the issue still present after the latest update ?

**Comment by Lab-8916100448256** [comment]
Hi,

[Edited]
I removed my previous comment.
I was also having this issue. But it turned out it was caused by my WiFi network.
