### ISSUE TITLE
The font is not in the middle in the vertical direction

### ISSUE THREAD

**Issue by lifedebug** [loboris/MicroPython_ESP32_psRAM_LoBo#129]
The font created with ttf2c_vc2003.exe is not in the middle in the vertical direction，Whether ttf2c_vc2003.exe has ‘intermediate’ parameters？

**Comment by loboris** [comment]
I don't have the sources for _ttf2c_vc2003.exe_, so I can't do anything about it.

I'm working on my own font converter program, but I'm not shure when it will be finished.

**Comment by lifedebug** [comment]
thanks ！Looking forward to your program！
