### ISSUE TITLE
rtc - ntp with tz handling leads to error

### ISSUE THREAD

**Issue by newmindJP** [loboris/MicroPython_ESP32_psRAM_LoBo#130]
after connecting to WiFi I try following code:

from machine import RTC
rtc = RTC()
rtc.ntp_sync(server="192.168.1.10", tz="CET-1CEST-2")

This leads to error -> ValueError: tz string length must be 3 - 64
I tried several options, but when ever I set a tz it leads to this error

after checking the code in file "MicroPython_BUILD/components/micropython/esp32/machine_rtc.c" I guess the problems relates to line 333
`if ((strlen(tzs) < 2) && (strlen(tzs) < 64)) {`
the correct code has to be
`if ((strlen(tzs) > 2) && (strlen(tzs) < 64)) {`

**Comment by loboris** [comment]
Yes it is a bug. Thank you for noticing that.
I'll fix it in the next update.

Until fixed, you can set the ime zone with
`sys.tz("CET-1CEST-2")`
and use `rtc.ntp_sync(server="192.168.1.10")` without setting the time zone.

That way the time zone is saved to NVS and will be restored after reset, power off or deepsleep wake up, so you have to set it only once.

**Comment by newmindJP** [comment]
thanks for the fast reply and info about the workaround - I'll do it in that way until it is fixed ...

**Comment by loboris** [comment]
It was fixed in the latest update.
