### ISSUE TITLE
Example needed how to communicate over I2C

### ISSUE THREAD

**Issue by untitledlt** [loboris/MicroPython_ESP32_psRAM_LoBo#131]
Could someone please provide an example how to send and receive data over I2C between master and slave?
I have initializes master and slave on two ESP32. 
`i2c.scan()` returns `[32]` on master, but i can not find any examples how to send and read data.

**Comment by loboris** [comment]
The Example on [Wiki page](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/i2c) is about I2C master/slave communication.
It is written for testing on the same ESP32 board, but it should be easy to separate master and slave parts for two ESP32 boards.

I2C instance **m** is for master, **s** for slave.
