### ISSUE TITLE
upip broken; fix exists but needs to be propagated

### ISSUE THREAD

**Issue by mmccool** [loboris/MicroPython_ESP32_psRAM_LoBo#133]
upip does not work due to an incorrect (recently changed) URL: see https://github.com/micropython/micropython/issues/3733
Note this is a *closed* issue... so the fix has already been made.
However, it still needs to be merged into this fork...

**Comment by loboris** [comment]
I have updated the url, the changes will be available after the next commit (probably tomorrow).

**Comment by mzdaniel** [comment]
On MicroPython ESP32_LoBo_v3.2.15 - 2018-05-10 on ESP32 board with ESP32:

The new release looks like is now looking at the correct URL, though ssl seems to need more work?
 
``` python 
upip.install('micropython-uasyncio')
Installing to: /flash/lib/
Installing micropython-uasyncio 2.0 from https://files.pythonhosted.org/packages/9d/a4/afaf98be714d3701d47c47b3b6aa3d5e52bf277fe8ceb9a2e3fdb05eaf86/micropython-uasyncio-2.0.tar.gz
mbedtls_ssl_handshake error: -7200
Error installing 'micropython-uasyncio': [Errno 5] EIO, packages may be partially installed
```

**Comment by Josverl** [comment]
Agree , the issue seems to be specific to mbedtls, although I have not tested with the standard yet.
Possibly this is related to : https://loboris.eu/forum/Thread-Bug-report-HTTPS-doesnt-work-flawlessly?highlight=mbedtls 
which is attributed to a 4K max mbedtls buffer even when using a PSRAM build

**Comment by loboris** [comment]
After the latest update, **upip** is working without problems.

`→ Component config → mbedTLS → TLS maximum message content length` must be set to a minimum of **8192** in _menuconfig_ (this is now the default value when the new sdkconfig is created).

**Comment by mzdaniel** [comment]
Thank you Boris!

Confirmed in MicroPython ESP32_LoBo_v3.2.17 - 2018-05-16 on ESP32 board with ESP32 .  Looks like we can bring this issue to rest.

```python
>>> from network import WLAN
>>> w = WLAN()
>>> w.active()
>>> w.active(True)
True
>>> w.connect('espnet', '12345678')
>>> w.ifconfig()
('192.168.43.124', '255.255.255.0', '192.168.43.1', '192.168.43.1')
>>> import upip
>>> import gc
>>> gc.collect()
>>> gc.mem_free()
63200
>>> upip.install('micropython-uasyncio')
Installing to: /flash/lib/
Warning: pypi.org SSL certificate is not validated
Installing micropython-uasyncio 2.0 from https://files.pythonhosted.org/packages/9d/a4/afaf98be714d3701d47c47b3b6aa3d5e52bf277fe8ceb9a2e3fdb05eaf86/micropython-uasyncio-2.0.tar.gz
Installing micropython-uasyncio.core 2.0 from https://files.pythonhosted.org/packages/66/45/372e657680a613ecb6d4d124157fa46f99d2072b4443476a20f39a82f961/micropython-uasyncio.core-2.0.tar.gz
>>> import uasyncio
>>> 

# The only thing to watch up for is free memory as upip requires plenty of 
# memory to do its job.

>>> gc.mem_free()
46384
>>> upip.install('micropython-uasyncio')
Installing to: /flash/lib/
Installing micropython-uasyncio 2.0 from https://files.pythonhosted.org/packages/9d/a4/afaf98be714d3701d47c47b3b6aa3d5e52bf277fe8ceb9a2e3fdb05eaf86/micropython-uasyncio-2.0.tar.gz
Error installing 'micropython-uasyncio': memory allocation failed, allocating 32768 bytes, packages may be partially installed
```

**Comment by loboris** [comment]
Regarding the insuficient memory, the **heap size** can now be set during runtime (reboot required) using the function:
`machine.SetHeapSize(value)`

> Set the new MicroPython heap size.
> The heap size is stored in the NVM and will be used on the next (and all consecutive) reboot.
>

**Comment by loboris** [comment]
I'll close the issue, please reopen if needed.
