### ISSUE TITLE
SPI

### ISSUE THREAD

**Issue by straga** [loboris/MicroPython_ESP32_psRAM_LoBo#14]
I am try code from
https://github.com/Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266/tree/master/examples/pair/rx

Boot loop.

But if flash standart micopython it works.

**Comment by loboris** [comment]
Could you be more specific about the issue (board used, error messages, error log, ...)

**Comment by straga** [comment]
I think it problem in your's SPI not support bits = 9 or 16.

**Comment by loboris** [comment]
Some bugs in spi driver are now fixed.
Tested with SX127x driver and works using files in
**MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/esp32/modules_examples/lora**
directory.
