### ISSUE TITLE
example needed for piezo buzzers

### ISSUE THREAD

**Issue by crxcv** [loboris/MicroPython_ESP32_psRAM_LoBo#143]
Hey there, 
is there any example for piezo-buzzers?
i have both - active and passive, tried with machine.DAC and machine.PWM but there's no sound on the buzzers. 

would be great if i get some help...

**Comment by kevinkk525** [comment]
Hey, this is pretty much the wrong place for this, it would be better to ask it on the forum.

Anyways, I use piezo-buzzers on my esp8266, but it's not tested on my esp32:

```
pin = PWM(Pin(self.pin, Pin.OUT), freq=freq)
pin.duty(0)
for duty in self.values:
  pin.duty(duty)
  time.sleep_ms(500)
pin.duty(0)
```

**Comment by crxcv** [comment]
thx kevin... also not working.
can u give me a link to the forum? 

if u mean micropython forum..  examples are working with the pyb module - but there's no pyb module ;)

**Comment by kevinkk525** [comment]
[https://loboris.eu/forum/index.php](https://loboris.eu/forum/index.php)

guess the link should be put somewhere more obvious.

**Comment by crxcv** [comment]
thx alot :)

**Comment by kevinkk525** [comment]
I just tested it on my esp32 and it works without any problems:

```
pwm=machine.PWM(22)
pwm.duty(50)
```

does your piezo work with an esp8266? does it work with 3.3V? I first bought one that did not really make a noise with 3.3V and the few mA that a gpio can handle.

**Comment by crxcv** [comment]
got it ;)
but can't figure out what went wrong...
same thing with ldr... values didn't change with hands on/off the ldr a few hours ago, but now works well 

perhabs the short break for machines & me was good ;)

but thx for ur help!
