### ISSUE TITLE
SOLVED: TypeError: '<' not supported between instances of 'PartitionDefinition' and 'PartitionDefinition'

### ISSUE THREAD

**Issue by davidm-public** [loboris/MicroPython_ESP32_psRAM_LoBo#147]
Ran into this error:

 `TypeError: '<' not supported between instances of 'PartitionDefinition' and 'PartitionDefinition'`

seems that `./BUILD.sh` needs python2

this worked  (from: https://github.com/espressif/arduino-esp32/issues/236 )

```shell
mkdir /tmp/bin
PATH=/tmp/bin:$PATH
ln -s /usr/bin/python2 /tmp/bin/python
```

**Comment by loboris** [comment]
You can explicitly set python2 in **menuconfig**:
`→ SDK tool configuration → Python 2 interpreter`, set to **`python2`** or **`/usr/bin/python2`** instead of default `python`
