### ISSUE TITLE
The files partitions_mpy.bin and phy_init_data.bin  are missing from pre build

### ISSUE THREAD

**Issue by nissimzur** [loboris/MicroPython_ESP32_psRAM_LoBo#16]
The files partitions_mpy.bin and phy_init_data.bin  are missing from the build
MicroPython_ESP32_psRAM_LoBo-master\MicroPython_BUILD\firmware\esp32\.. 
It can be nice to have a full set compiled with some user application in the file system to test all without the need for rebuild.

**Comment by loboris** [comment]
Thank you for noticing.
I will correct it.

**Comment by loboris** [comment]
This was fixed in the latest commit.
