### ISSUE TITLE
Using a not connected I2C-object results in RAM leak

### ISSUE THREAD

**Issue by kevinkk525** [loboris/MicroPython_ESP32_psRAM_LoBo#164]
In my program I use I2C to read my HTU which works fine of course.
But if not HTU is connected and I try to read the values the free RAM will decrase. Every 2 reading attempts resulting in "I2C bus error (-1)" cost me 1kB of RAM until the microcontroller crashes with a memory allocation error.
(Garbage collection is executed often between the readings)

ESP32_LoBo_v3.2.12 - 2018-04-18

**Comment by carterw** [comment]
Did you do scan() first to see if it is present?

**Comment by kevinkk525** [comment]
No the library just assumes that it is present.
Works on the ESP8266 without the ram leak and just throws an error. I have not seen a htu library yet that scans first.
Also you would have to scan before any read as your connected device could be destroyed and therefore unavailable. That would be a lot of scans.

**Comment by carterw** [comment]
Merely suggesting a workaround. I invoke the scan myself first before invoking a driver for a device. An I2C device might be subsequently unplugged, but that's a different problem.

**Comment by kevinkk525** [comment]
That's true but I actually just stumbeled onto that bug when I was trying my code on an unconnected esp32 for general workability (import errors, general functionality, ...). 
Never had any problem with it before.

**Comment by loboris** [comment]
Thank you for reporting this issue.
It will be fixed in the next update.
