### ISSUE TITLE
Build firmware under windows (msys2) failed

### ISSUE THREAD

**Issue by df6dbf** [loboris/MicroPython_ESP32_psRAM_LoBo#167]
Build Firmware fails since last update. Started mingw32.exe changed the Directorys as described. git pull to get the latest repository. 

./BUILD.sh clean is ok
./BUILD.sh menuconfig also runs without any error.
./BUILD.sh all fails - see attached screenshot from my win7pro-64bit machine.

Kind regards, 
Holger
![screenshot 2018-06-07 19 01 09](https://user-images.githubusercontent.com/19621920/41114991-5965dc20-6a86-11e8-8744-92e33b7d6541.png)

**Comment by suli3** [comment]
How about move the msys32 folder to D:\， then retry?

**Comment by df6dbf** [comment]
I dont have a Drive D on this machine. :)  The odd thing is that die building process worked before the last update. seems ths file stdint.h is missing.

**Comment by df6dbf** [comment]
Finally installed the toolchain and the respository completly new. Now it works.
