### ISSUE TITLE
The file spiffs_image.img is build to one directory and flash old spiffs_image.img from another directory

### ISSUE THREAD

**Issue by nissimzur** [loboris/MicroPython_ESP32_psRAM_LoBo#17]
Is this a BUG?
The file spiffs_image.img is build to one directory and flash old spiffs_image.img from another directory. 

./BUILD.sh makefs
Creat at directory :
 /MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/**build**/spiffs_image.img)

./BUILD.sh copyfs
Copy to ESP32 from directory  : 
/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/**components/spiffs_image**/spiffs_image.img

Reset reason: Power on reset Wakeup: Power on wake
D (142) intr_alloc: Connected src 22 to int 4 (cpu 1)
vfs_native: f_mount failed (13)
(152) vfs_native: ** Formatting Flash FATFS partition **
vfs_native: ** Mounting again
OSError: [Errno 2] ENOENT
MicroPython ESP32_LoBo_v2.0.4 - 2017-10-08 on ESP32 board with ESP32
Type "help()" for more information.
>>>

**Comment by loboris** [comment]
`./BUILD.sh copyfs` is used to flash the **default** spiffs image.
`./BUILD.sh makefs` is used to only **create** the image
`./BUILD.sh flashfs` is used to **create** and **flash** the image

**Comment by nissimzur** [comment]
This been used. 
Still no main.py on ESP32
And no sample code has been loaded. 
______________________________________________________________________________________________

FreeRTOS running on BOTH CORES, MicroPython task started on App Core.

uPY stack size = 19456 bytes
uPY  heap size = 81920 bytes

D (134) intr_alloc: Connected src 34 to int 3 (cpu 1)[0m
Reset reason: Power on reset Wakeup: Power on wake
D (144) intr_alloc: Connected src 22 to int 4 (cpu 1)[0m
Registering SPIFFS file system to VFS

Mounting SPIFFS files system
----------------
  Start address: 0x280000; Size 1024 KB
    Work buffer: 2048 B @ 0x3ffdf594
     FDS buffer:  384 B @ 0x3ffdfd98
     Cache size: 2048 B @ 0x3ffc8178
----------------
Mounted.
----------------

Filesystem size: 980657 B
           Used: 140811 B
           Free: 839846 B
----------------

[0;31mE (190) vfs_native: Error creating 'boot.py'[0m
OSError: [Errno 2] ENOENT
OSError: [Errno 2] ENOENT
MicroPython ESP32_LoBo_v2.0.4 - 2017-10-08 on ESP32 board with ESP32
Type "help()" for more information.
>>> **import os
>>> os.listdir()**
**Traceback (most recent call last):
File "<stdin>", line 1, in <module>
OSError: [Errno 2] ENOENT**

**Comment by loboris** [comment]
Please look at my last comment at https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/15

**Comment by loboris** [comment]
**You can check detailed procedure and logs** in my last comment at https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/15
