### ISSUE TITLE
error on _thread.start_new_thread(

### ISSUE THREAD

**Issue by nissimzur** [loboris/MicroPython_ESP32_psRAM_LoBo#18]
Every time _thread.start_new_thread(..) is called, runtime error occurred.
for example:

import _thread
import time
 
def testThread(sleep_time):
  while True:
    print("Hello from thread", sleep_time)
    time.sleep(sleep_time)

 
_thread.start_new_thread(testThread, (1,))
_thread.start_new_thread(testThread, (2,))
_thread.start_new_thread(testThread, (3,))

**Comment by loboris** [comment]
The right syntax is:
`_thread.start_new_thread("th_name", th_func, args[, kwargs])`
You must give the thread name string.

[Documentation](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/docs/thread.md)
