### ISSUE TITLE
build compilation error

### ISSUE THREAD

**Issue by carterw** [loboris/MicroPython_ESP32_psRAM_LoBo#181]
I pulled the most recent commit and am seeing a build error.

MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/py/../extmod/vfs_native.c:882:31: error: expected '}' before ';' token
    .allocation_unit_size   = 0;

Removing that trailing semicolon fixes it...

**Comment by loboris** [comment]
Thank you for reporting.
I've not tested the compilation with FatFS selected as internal FS.
Fixed and commited.

**Comment by carterw** [comment]
Thanks for fixing.
