### ISSUE TITLE
Pin.irq is now Pin.irqvalue ?

### ISSUE THREAD

**Issue by carterw** [loboris/MicroPython_ESP32_psRAM_LoBo#182]
Did the Pin class change? Breaks existing code.

In firmware prior to today's commit;
>>> from machine import Pin
>>> help(Pin)
object \<class 'Pin'\> is of type type
  init -- \<function\>
  value -- \<function\>
  irq -- \<function\>

In firmware built with today's commit;
>>> from machine import Pin
>>> help(Pin)
object <class 'Pin'> is of type type
  __del__ -- \<function\>
  init -- \<function\>
  value -- \<function\>
  irqvalue -- \<function\>           <<<<

**Comment by carterw** [comment]
Actually it looks like Pin.irq is simply missing. Changing it to Pin.irqvalue results in;
TypeError: function does not take keyword arguments

I guess Pin.irqvalue() is just a new way to see how the irq is currently set up.

**Comment by loboris** [comment]
Yes, the machine.Pin was refactored, see the [Wiki](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/pin).
I think it makes much more sense that way, and many more features are anailable.
It was changed in commit from June 4, not in todays commit.

**Comment by carterw** [comment]
Wow, okay. Will investigate that.
