### ISSUE TITLE
Missing zones.csv

### ISSUE THREAD

**Issue by cwt** [loboris/MicroPython_ESP32_psRAM_LoBo#2]
On menuconfig on "MicroPython -> Time zone", the help states that **You can use 'zones.csv' file to find the time zone string.** However, file `MicroPython_BUILD/components/micropython/docs/zones.csv` was removed by your last  commit. So now I have to get timezone value from the previous commit instead.

**Comment by loboris** [comment]
Thank you, it will be pushed back on next commit.
The _zones.csv_ was taken from [this repository](https://github.com/nayarsystems/posix_tz_db)
