### ISSUE TITLE
error in $ git clone --recursive https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo.git

### ISSUE THREAD

**Issue by nissimzur** [loboris/MicroPython_ESP32_psRAM_LoBo#20]
$ git clone --recursive https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo.git
Cloning into 'MicroPython_ESP32_psRAM_LoBo'...
remote: Counting objects: 13160, done.
remote: Compressing objects: 100% (254/254), done.
remote: Total 13160 (delta 94), reused 146 (delta 52), pack-reused 12849
Receiving objects: 100% (13160/13160), 693.07 MiB | 330.00 KiB/s, done.
Resolving deltas: 100% (3967/3967), done.
Checking out files: 100% (1653/1653), done.
': not a valid identifierline 88: export: `dashless
Submodule 'micropython-lib' (https://github.com/micropython/micropython-lib) registered for path 'micropython-lib'
Cloning into '/MicroPython_ESP32_psRAM_LoBo/micropython-lib'...
remote: Counting objects: 5798, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 5798 (delta 15), reused 29 (delta 8), pack-reused 5750
Receiving objects: 100% (5798/5798), 1.03 MiB | 292.00 KiB/s, done.
Resolving deltas: 100% (3020/3020), done.
': not a valid identifierline 88: export: `sha1 
': not a valid identifierline 88: export: `displaypath
Submodule path '': checked out 'c265899cb7f0743fc7a11b2c240dce44c6855579'

nissim@win7 MINGW32 /

**Comment by loboris** [comment]
I'll check the Windows cloning process tomorrow.
You don't have to use `git clone --recursive`, the only submodule is _micropython-lib_, it will probably be removed in the next commit (it is not used anywhere).

**Comment by loboris** [comment]
I've tried this on Windows and got the similar error:
```
Boris@WINSERVER2012R2 MINGW32 ~/esp32/MicroPython
$ git submodule update --init --recursive
”: nije ispravan identifikator 88: export: „dashless
Submodule 'micropython-lib' (https://github.com/micropython/micropython-lib) registered for path 'micropython-lib'
Cloning into '/home/Boris/esp32/MicroPython/micropython-lib'...
”: nije ispravan identifikator 88: export: „sha1
”: nije ispravan identifikator 88: export: „displaypath
Submodule path '': checked out 'c265899cb7f0743fc7a11b2c240dce44c6855579'
```
but the module **was clonned successfully**.
I'm not working with Windows, so I can't give you the qualified explanation for that, is is probably caused by something specific to MINGW git implementation.

**Comment by loboris** [comment]
Submodule **micropython-lib** is now removed.
No need to use `git clone --recursive`.
