### ISSUE TITLE
DHT sensor readings get truncated.

### ISSUE THREAD

**Issue by theozed** [loboris/MicroPython_ESP32_psRAM_LoBo#203]
Hi,

I've found a problem in the code for the DTH temperature and humidity sensor, and also have a solution.

When a DTH22 sensor is used, the results are always truncated after the decimal place. The sensor itself reports temperature and humidity with 1 digit after the decimal place, but this gets lost. eg 19.2 becomes 19.0. 

My code to read the sensor in repl with the sensor on pin 4:
```
MicroPython ESP32_LoBo_v3.2.20 - 2018-06-28 on ESP32 board with ESP32
Type "help()" for more information.
>>> import machine
>>> dht = machine.DHT(4, machine.DHT.DHT2X)
>>> dht.read()
(True, 19.0, 72.0)
```
The temperature goes 17.0, 18.0, 19.0 etc.

Solution:
The problem lies in the file "machine_dht.c", in the function "ldht_compute_data2x" at line 281.
MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/esp32/machine_dht.c
This function converts the raw bytes read from the sensor to temp and humidity values, but type casts the conversion to integers rather than doubles, causing the truncation.

```
static int ldht_compute_data2x( uint8_t *data, double *temp, double *humi )
{
  *humi = (uint16_t)((data[0] * 256 + data[1])) / 10;
  *temp = (uint16_t)(((data[2] & 0x7f) * 256 + data[3])) / 10;

  if (data[2] & 0x80)
    *temp = - *temp;

  uint8_t sum = data[0] + data[1] + data[2] + data[3];
  return sum == data[4] ? LDHT_OK : LDHT_ERROR_CHECKSUM;
}
```

The fix is simply changing two lines to:
```
*humi = (double)((data[0] * 256 + data[1])) / 10;
*temp = (double)(((data[2] & 0x7f) * 256 + data[3])) / 10;
```
After this change, the sensor results are returned with full precision.

**Comment by loboris** [comment]
Thanks for the report.
This is fixed in the latest update.
