### ISSUE TITLE
update has somebug.

### ISSUE THREAD

**Issue by Avi-TelnT** [loboris/MicroPython_ESP32_psRAM_LoBo#21]
avi@winpc MINGW32 /MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD
$ git pull
Already up-to-date.

avi@winpc MINGW32 /MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD
$ git submodule update --init --recursive
**': not a valid identifierline 88: export: `dashless**

**Comment by loboris** [comment]
I'll check the Windows build.

**Comment by loboris** [comment]
I've tried this on Windows and got the similar error:
```
Boris@WINSERVER2012R2 MINGW32 ~/esp32/MicroPython
$ git submodule update --init --recursive
”: nije ispravan identifikator 88: export: „dashless
Submodule 'micropython-lib' (https://github.com/micropython/micropython-lib) registered for path 'micropython-lib'
Cloning into '/home/Boris/esp32/MicroPython/micropython-lib'...
”: nije ispravan identifikator 88: export: „sha1
”: nije ispravan identifikator 88: export: „displaypath
Submodule path '': checked out 'c265899cb7f0743fc7a11b2c240dce44c6855579'
```
but the module **was clonned successfully**.
I'm not working with Windows, so I can't give you the qualified explanation for that, is is probably caused by something specific to MINGW git implementation.
