### ISSUE TITLE
Example "ssd1306_i2c_example.py" for ESP32 does'nt work

### ISSUE THREAD

**Issue by schroepfer** [loboris/MicroPython_ESP32_psRAM_LoBo#21]
>>> from ssd1306 import SSD1306_I2C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ssd1306.py", line 5, in <module>
ImportError: **no module named 'framebuf'**

**Comment by loboris** [comment]
Framebuffer is not enabled by default.
You should enable it in **menuconfig**: `→ MicroPython → Modules → Enable framebuffer`
