### ISSUE TITLE
Pin value doesn't change

### ISSUE THREAD

**Issue by Euter2** [loboris/MicroPython_ESP32_psRAM_LoBo#213]
Lolin D32 Pro with newest prebuild firmware esp32_psram_all

*Steps to reproduce*
>>>from machine import Pin
>>>led = Pin(5, Pin.OUT)
>>>led.value(1)
>>>led.value()
>>>0
>>>led.value(0)
>>>led.value()
>>>0
>>>led.value(1)
>>>led.value()
>>>0

LED blinks so voltage changes but led.value() returns wrong value.

**Comment by loboris** [comment]
From Wiki:
**`pin.value([val])`**
Get or set the pin value.
If no argument is given, returns the current pin value (level), 0 or 1
It the val argument is given, set the pin level. val can be 0, 1, False or True

**Note:** If the pin is set to output-only mode (**`OUT`** or `OUT_OD`), the returned value will always be 0
If you want to get the value of the output pin, it must be se to **`INOUT`** or INOUT_OD mode.
