### ISSUE TITLE
The file boot.py is not been used in buildfs

### ISSUE THREAD

**Issue by Avi-TelnT** [loboris/MicroPython_ESP32_psRAM_LoBo#22]
The file boot.py is **not been used** in makefs
c:\msys32\MicroPython_ESP32_psRAM_LoBo\MicroPython_BUILD\components\spiffs_image\image\boot.py

This is my boot.py
import sys
sys.path[1] = '/flash/lib'
print("=== my boot.py is running===")

I add command as print("=== my boot.py is running ===") in disk boot.py and it is not shows on the ESP32 boot.py

The file boot.py is created automatically by esp32 default boot. Since print text I added was not on esp32 boot.py file.

The file main.py is not added too to  by ./BUILD.sh makefs and after that ./BUILD.sh flashfs

If added main.py manually to ESP32, **it does run automatically** on next esp32 boot.

It has been marked in ./BUILD.sh menuconfig to create SPIFFS filesystem image
Commands ./BUILD.sh makefs and after that ./BUILD.sh flashfs been used. 
./BUILD.sh copyfs same problem.

**Comment by loboris** [comment]
Please look at the last comment at https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/15
