### ISSUE TITLE
It correct works gc.mem_free() and gc.mem_alloc() ?

### ISSUE THREAD

**Issue by straga** [loboris/MicroPython_ESP32_psRAM_LoBo#22]
import gc
gc.collect()
gc.mem_free()
gc.mem_alloc()

after call gc.mem_alloc() alocate shows more and more.

[Video Example](https://youtu.be/Q2YLwu4H5FM)

**Comment by loboris** [comment]
Every time some Python code is executed some memory (from heap) is allocated.
The garbage (not used) memory is freed when garbage collector is run. It can happen on request (when you execute `gc.collect()` or automatically, when the gc threshold usage is reached.
You can check and set the threshold value using `gc.threshold()`. The initial value is ~ 75%  of available heap.
If you are using psRAM, there are a lot of heap space, so automatic garbage collector may never run.
You can occasionally run `gc.collect()` in you code.
