### ISSUE TITLE
how to get font .ttf file

### ISSUE THREAD

**Issue by EeeeBin** [loboris/MicroPython_ESP32_psRAM_LoBo#234]
For some reason, I need to get these font _.ttf_ file,where can I get them?
``      
  "FONT_Default", "FONT_DejaVu18", "FONT_DejaVu24", "FONT_Ubuntu", "FONT_Comic", "FONT_Minya", "FONT_Tooney", "FONT_Small", "FONT_DefaultSmall",
``

**Comment by loboris** [comment]
The sources are [here](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/tree/master/MicroPython_BUILD/components/micropython/esp32/libs/tft).

**Comment by EeeeBin** [comment]
not this, need like DejaVu.ttf

**Comment by loboris** [comment]
A large number of TTF fonts is included in any Linux or Windows OS. DejaVu is one of the most commont fonts.
You can also get large number of fonts from Internet (for example [FontSquirrel](https://www.fontsquirrel.com)).
