### ISSUE TITLE
[Wiki] - rtc.read() and rtc.read_string() have incorrect return type

### ISSUE THREAD

**Issue by chrisb2** [loboris/MicroPython_ESP32_psRAM_LoBo#244]
In the Wiki for the machine.RTC class.

[rtc.read()](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/rtc#rtcreadpos) should say:
> Read integer (32-bit) from the position pos in RTC memory.
> Return an integer if one has been written to the position, or _None_ otherwise.

[rtc.read_string()](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/rtc#rtcread_string) should say:
> Read the string from RTC memory.
> Return a string if one has been written to the position, or _None_ otherwise.

**Comment by loboris** [comment]
Thank you, the Wiki is [updated](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/rtc#rtcreadpos).
The acctual behaviour is slightly different than your observation.

**Comment by chrisb2** [comment]
Thank you, thats really clear.
