### ISSUE TITLE
wiki mqtt mqtt.status()

### ISSUE THREAD

**Issue by oldfartradioman** [loboris/MicroPython_ESP32_psRAM_LoBo#25]
mqtt.status()

Returns the status of mqtt client task.

The status is returned as tuple: (num_stat, description).
Possible values are:
(0, "Connected")
(1, "Disconnected")
(2, "Stopping")
(3, "Stopped")

Connected and Disconnected are reversed

**Comment by loboris** [comment]
Thank you for informing about that.
It is fixed now.
