### ISSUE TITLE
OTA (ota.set_bootpart(partition))

### ISSUE THREAD

**Issue by bdespatis** [loboris/MicroPython_ESP32_psRAM_LoBo#26]
Hi,

I was able to create partition with flash -a [size in kb] each time I flash, if I am not using this option, it is 64 KB only for both partition ... Very strange (not 1 MB). I did not tried yet the 3 partitions version.

Also, I cannot access the function set_bootpart. Like if the partition was not accessible whatever the name (MicroPython, MicroPython_1, MicroPython_2). So I tried the start pointed to the example server. I was able to update and boot.

Let's hope it is a simple modification.

Regards,
Benoit

**Comment by loboris** [comment]
The minimal firmware partition size is determined by the size of the `build/MicroPython.bin` if it exists or set to 1024 kB if not.
Thre was a bug in `BUILD.sh` which caused the partition size to be set 64 kB if `build/MicroPython.bin` was not found.
It is fixed and the changes commited. 
`BUILD.sh` will fail if correct partition size cannot be determined.

[Ota Wiki](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/ota) was updated with more information.

In `ota.set_bootpart()`, only change to factory partition was allowed.
It is changed in the latest commit, so setting any partition as boot is now possible (if the partition exists and contains the valid application).

**Comment by bdespatis** [comment]
Like always, you are the best ! I will update mine and check it.
