### ISSUE TITLE
Ethernet Drivers & Your Forum

### ISSUE THREAD

**Issue by diginfo** [loboris/MicroPython_ESP32_psRAM_LoBo#26]
Hi;

First, thanks so much for all your work, I have been waiting for a good ESP32 build since early this year, the way you have made the build process so simple and configurable is very nice.

I think you probably need your own forum now, as the posts on micropython.org are not sorted and it's quite difficult to follow if you are looking for specific info :-)

Anyway, I see that you have notes that these were updated 3 months agon, but have you proven these ethernet drivers to work on your ESP32 repo ??

https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/tree/master/MicroPython_BUILD/components/micropython/drivers/wiznet5k/ethernet

Thanks again

**Comment by loboris** [comment]
Those drivers are from the original MicroPython, I've not tested them yet.
I have the module, but it is of lower priority and will be tested in a month or two.

**Comment by loboris** [comment]
I'll close this issue until the drivers are not tested.
