### ISSUE TITLE
you are using a different I2C library than the standard ESP32 MicroPython distribution?

### ISSUE THREAD

**Issue by rasmorthil** [loboris/MicroPython_ESP32_psRAM_LoBo#27]
Your MicroPython distribution is exactly what I am looking for (wear leveling, SPIFFS, etc.)!

However I am having trouble using an I2C-based SSD1306 OLED with your version, because it's missing the normal "primitive I2C operations" present in the standard MicroPython-esp32 distribution.

Standard distribution ([https://github.com/micropython/micropython-esp32/blob/esp32/extmod/machine_i2c.c](https://github.com/micropython/micropython-esp32/blob/esp32/extmod/machine_i2c.c)):

    STATIC const mp_rom_map_elem_t machine_i2c_locals_dict_table[] = {
        { MP_ROM_QSTR(MP_QSTR_init), MP_ROM_PTR(&machine_i2c_init_obj) },
        { MP_ROM_QSTR(MP_QSTR_scan), MP_ROM_PTR(&machine_i2c_scan_obj) },
    
        // primitive I2C operations
        { MP_ROM_QSTR(MP_QSTR_start), MP_ROM_PTR(&machine_i2c_start_obj) },
        { MP_ROM_QSTR(MP_QSTR_stop), MP_ROM_PTR(&machine_i2c_stop_obj) },
        { MP_ROM_QSTR(MP_QSTR_readinto), MP_ROM_PTR(&machine_i2c_readinto_obj) },
        { MP_ROM_QSTR(MP_QSTR_write), MP_ROM_PTR(&machine_i2c_write_obj) },
    
        // standard bus operations
        { MP_ROM_QSTR(MP_QSTR_readfrom), MP_ROM_PTR(&machine_i2c_readfrom_obj) },
        { MP_ROM_QSTR(MP_QSTR_readfrom_into), MP_ROM_PTR(&machine_i2c_readfrom_into_obj) },
        { MP_ROM_QSTR(MP_QSTR_writeto), MP_ROM_PTR(&machine_i2c_writeto_obj) },
    
        // memory operations
        { MP_ROM_QSTR(MP_QSTR_readfrom_mem), MP_ROM_PTR(&machine_i2c_readfrom_mem_obj) },
        { MP_ROM_QSTR(MP_QSTR_readfrom_mem_into), MP_ROM_PTR(&machine_i2c_readfrom_mem_into_obj) },
        { MP_ROM_QSTR(MP_QSTR_writeto_mem), MP_ROM_PTR(&machine_i2c_writeto_mem_obj) },
    };

Your distribution ([https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/esp32/machine_hw_i2c.c](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/esp32/machine_hw_i2c.c)):

    STATIC const mp_rom_map_elem_t machine_hw_i2c_locals_dict_table[] = {
        { MP_ROM_QSTR(MP_QSTR_init),                (mp_obj_t)&machine_hw_i2c_init_obj },
        { MP_ROM_QSTR(MP_QSTR_deinit),              (mp_obj_t)&machine_hw_i2c_deinit_obj },
        { MP_ROM_QSTR(MP_QSTR_scan),                (mp_obj_t)&machine_hw_i2c_scan_obj },
    
        // standard bus operations
        { MP_ROM_QSTR(MP_QSTR_readfrom),            (mp_obj_t)&machine_hw_i2c_readfrom_obj },
        { MP_ROM_QSTR(MP_QSTR_readfrom_into),       (mp_obj_t)&machine_hw_i2c_readfrom_into_obj },
        { MP_ROM_QSTR(MP_QSTR_writeto),             (mp_obj_t)&machine_hw_i2c_writeto_obj },
    
        // memory operations
        { MP_ROM_QSTR(MP_QSTR_readfrom_mem),        (mp_obj_t)&machine_hw_i2c_readfrom_mem_obj },
        { MP_ROM_QSTR(MP_QSTR_readfrom_mem_into),   (mp_obj_t)&machine_hw_i2c_readfrom_mem_into_obj },
        { MP_ROM_QSTR(MP_QSTR_writeto_mem),         (mp_obj_t)&machine_hw_i2c_writeto_mem_obj },
    
        { MP_OBJ_NEW_QSTR(MP_QSTR_MASTER),          MP_OBJ_NEW_SMALL_INT(I2C_MODE_MASTER) },
    };

The I2C implementation of the standard MicroPython SSD1306 driver included in your distribution uses the "write" function:

    def write_data(self, buf):
        self.temp[0] = self.addr << 1
        self.temp[1] = 0x40 # Co=0, D/C#=1
        self.i2c.write(self.temp)
        self.i2c.write(buf)

As such, whey trying to use an I2C-based SSD1306 OLED display with your distribution, it fails:

    MicroPython ESP32_LoBo_v2.0.4 - 2017-10-08 on ESP32 board with ESP32
    Type "help()" for more information.
    >>>
    >>> import ssd1306_test
    D (125976) intr_alloc: Connected src 49 to int 9 (cpu 1)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "ssd1306_test.py", line 47, in <module>
      File "ssd1306.py", line 109, in __init__
      File "ssd1306.py", line 37, in __init__
      File "ssd1306.py", line 64, in init_display
      File "ssd1306.py", line 89, in show
      File "ssd1306.py", line 119, in write_data
    AttributeError: 'I2C' object has no attribute 'write'
    >>>

Do you have any ideas how to fix this?

Thank you very much for your incredible work on this project!

**Comment by loboris** [comment]
There was a bug in **ssd1306.py**. I've fixed it a couple of days ago, the changes will be pusshed soon (I'm working on some other updates).
Look at [this forum post](https://forum.micropython.org/viewtopic.php?f=18&t=3764&start=10#p22616) for more datails and instructions how to fix it.

**Comment by rasmorthil** [comment]
OK, works great - thanks!

Also, just a quick note - when I build with -j# then there are race conditions that cause "framebuf" to not appear in my build, even though the build is successful.  If I build without "-j#" then it works fine.  So in this case build success doesn't mean that the build will actually work properly.

**Comment by loboris** [comment]
I've made some changes in BUILD.sh which should solve this issue.
There are many new modules, changes and bugfixes, I'll push it today or tomorrow, still testing some things...

**Comment by rasmorthil** [comment]
Thank you very much - can't wait to give it a try!

**Comment by loboris** [comment]
Issues solved, please reopen if needed.
