### ISSUE TITLE
Should pwm.duty() accept a float?

### ISSUE THREAD

**Issue by oldfartradioman** [loboris/MicroPython_ESP32_psRAM_LoBo#27]
I am trying to contol a hobby servo with pwm:
from machine import PWM 
pwm=PWM(27, freq=50)
>>> pwm.duty(1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert float to in  <module>

Should be seeing 15 bit resolution, with (0-100)% seeing less than 7.
Perhaps I am missing something?

**Comment by loboris** [comment]
`pwm.duty() `accepts float value from the commit cc836a3c5d68947b46bce4c5e5404826bbc47ec1, Jan 17.

Please pull the newest commits.
