### ISSUE TITLE
build error when power management is enabled

### ISSUE THREAD

**Issue by carterw** [loboris/MicroPython_ESP32_psRAM_LoBo#28]
I enabled power management and getting a compilation error.
component config->power management->support for power management
(all other options on that panel remained disabled)

CC build/driver/spi_master_utils.o
In file included from /home/bill/esp32/LoBo/MicroPython_ESP32_psRAM_LoBo/Tools/esp-idf/components/driver/include/driver/spi_master_utils.h:20:0,
                 from /home/bill/esp32/LoBo/MicroPython_ESP32_psRAM_LoBo/Tools/esp-idf/components/driver/./spi_master_utils.c:21:
/home/bill/esp32/LoBo/MicroPython_ESP32_psRAM_LoBo/Tools/esp-idf/components/driver/include/driver/spi_master_internal.h:55:5: error: unknown type name 'esp_pm_lock_handle_t'
     esp_pm_lock_handle_t pm_lock;
/home/bill/esp32/LoBo/MicroPython_ESP32_psRAM_LoBo/Tools/esp-idf/components/driver/./spi_master_utils.c: In function 'spi_set_speed':
/home/bill/esp32/LoBo/MicroPython_ESP32_psRAM_LoBo/Tools/esp-idf/components/driver/./spi_master_utils.c:447:9: warning: unused variable 'effclk' [-Wunused-variable]
     int effclk=handle->clk_cfg.eff_clk;

**Comment by loboris** [comment]
Power management implementation is planned for February/March...
