### ISSUE TITLE
upip error -29184

### ISSUE THREAD

**Issue by supersjimmie** [loboris/MicroPython_ESP32_psRAM_LoBo#291]
```
>>> upip.install('aenum')
Installing to: /flash/lib/
Error installing 'aenum': -29184, packages may be partially installed

```
I think it's not really directly related to this specific micropython, but I hope you can help me starting...  When a package-name is incorrect it says "Package not found" so I assume the name is correct, but how can I figure out why this strange -29184 error occurs?

**Comment by curlyz** [comment]
it is the socket problem , possibly due to big socket.recv()

**Comment by curlyz** [comment]
this happen due to ssl verification , in Python , we can disable this with adding verify = False inside requests method , not in micropython. :((

**Comment by curlyz** [comment]
this is the server problem, sometimes they forgot to update their ssl certificate, please close this issue 
@supersjimmie
