### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by mikey60** [loboris/MicroPython_ESP32_psRAM_LoBo#3]
After I cloned your repository an tried to build `menuconfig` I got the following error.  I can build and download programs using esp-idf.

`mike@ubuntu:~/esp/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD$ ./BUILD.sh menuconfig psram

Building MicroPython for ESP32 with esp-idf psRAM branch

MENUCONFIG
/home/mike/esp/MicroPython_ESP32_psRAM_LoBo/esp-idf_psram/tools/kconfig/mconf: 1: /home/mike/esp/MicroPython_ESP32_psRAM_LoBo/esp-idf_psram/tools/kconfig/mconf: Syntax error: "(" unexpected
'make menuconfig' FAILED!
`

**Comment by loboris** [comment]
Have you made any changes after the cloning ?
Can you run make menuconfig for other esp-idf projects?

For test I've cloned the repository into new directory and it builds without error:
```
boris@UbuntuMate:/home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD$ ./BUILD.sh menuconfig psram
unpacking 'esp-idf'
unpacking 'esp-idf_psram'
unpacking 'xtensa-esp32-elf'
unpacking 'xtensa-esp32-elf_psram'

Building MicroPython for ESP32 with esp-idf psRAM branch

DEFCONFIG
#
# configuration written to /home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/sdkconfig
#
MENUCONFIG


Your configuration changes were NOT saved.

configuration written to /home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/sdkconfig

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

GENCONFIG
#
# configuration written to /home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/sdkconfig
#
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
/home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/esp-idf_psram/make/component_wrapper.mk:138: warning: overriding recipe for target 'libmicropython.a'
/home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/py/mkrules.mk:136: warning: ignoring old recipe for target 'libmicropython.a'
OK.

boris@UbuntuMate:/home/LoBo2_Razno/ESP32/MicroPython/test/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD$ ./BUILD.sh -j2 psram

Building MicroPython for ESP32 with esp-idf psRAM branch

================================
Building MicroPython firmware...
================================
OK.
Build complete.
You can now run ./BUILD.sh flash
to deploy the firmware to ESP32
--------------------------------

```

**Comment by mikey60** [comment]
Thank you for your quick reply.  I deleted the directory, started over and still get the same error.  Do I need to clone the original micropython-esp32 repository?  The complete terminal session starting at the cloning of the repository is shown below. 

    `mike@ubuntu:~/esp$ git clone --recursive https://github.com/loboris/MicroPython_
ESP32_psRAM_LoBo.git
Cloning into 'MicroPython_ESP32_psRAM_LoBo'...
remote: Counting objects: 12102, done.
remote: Total 12102 (delta 0), reused 0 (delta 0), pack-reused 12102
Receiving objects: 100% (12102/12102), 465.10 MiB | 18.44 MiB/s, done.
Resolving deltas: 100% (3356/3356), done.
Checking connectivity... done.
Submodule 'ampy' (https://github.com/adafruit/ampy) registered for path 'ampy'
Submodule 'micropython-lib' (https://github.com/micropython/micropython-lib) reg
istered for path 'micropython-lib'
Cloning into 'ampy'...
remote: Counting objects: 98, done.
remote: Total 98 (delta 0), reused 0 (delta 0), pack-reused 98
Unpacking objects: 100% (98/98), done.
Checking connectivity... done.
Submodule path 'ampy': checked out 'b693e22b273804bdf5a8e33cec7dd3bf4e484eab'
Cloning into 'micropython-lib'...
remote: Counting objects: 5603, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 5603 (delta 24), reused 45 (delta 12), pack-reused 5537
Receiving objects: 100% (5603/5603), 1.01 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2895/2895), done.
Checking connectivity... done.
Submodule path 'micropython-lib': checked out 'c265899cb7f0743fc7a11b2c240dce44c
6855579'
mike@ubuntu:~/esp$ cd MicroPython_ESP32_psRAM_LoBo/
mike@ubuntu:~/esp/MicroPython_ESP32_psRAM_LoBo$ cd MicroPython_BUILD/
mike@ubuntu:~/esp/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD$ ./BUILD.sh men
uconfig psram
unpacking 'esp-idf'
unpacking 'esp-idf_psram'
unpacking 'xtensa-esp32-elf'
unpacking 'xtensa-esp32-elf_psram'

Building MicroPython for ESP32 with esp-idf psRAM branch

DEFCONFIG
/home/mike/esp/MicroPython_ESP32_psRAM_LoBo/esp-idf_psram/tools/kconfig/conf: 1:
 /home/mike/esp/MicroPython_ESP32_psRAM_LoBo/esp-idf_psram/tools/kconfig/conf: S
yntax error: ")" unexpected
'make menuconfig' FAILED!

mike@ubuntu:~/esp/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD$`

**Comment by mikey60** [comment]
Oops, I did not mean to close the issue.  Thank you for your quick reply.  I deleted the directory, started over and still get the same error.  Do I need to clone the original micropython-esp32 repository?  The complete terminal session starting at the cloning of the repository is shown in the attached file.

[error.txt](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/files/1264417/error.txt)

**Comment by mikey60** [comment]
Yes, I can run make menuconfig for other esp-idf projects.

**Comment by loboris** [comment]
It is strange.
To be shure, I've tried it on fresh Ubuntu 16.04 instalation in VirtualBox (from _ubuntu-16.04.1-server-amd64.iso_). This is the only steps I've made:

1. Installed Ubuntu 16.04 in VirtualBox, minimal server installation, only ssh selected as extra package
2. After installation and first boot run sudo apt-get update & apt-get upgrade
3. Installed packages needed for esp-idf compile: **sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial**
4. Cloned the repository, _git clone https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo.git_
5. cd to MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD
6. run ./BUILD.sh menuconfig psram  -  **NO ERROR**
7. ./BUILD.sh all psram  also passed without error

I really don't have any idea what could cause the error you get.
Maybe you could try the same procedure in VirtualBoy I've did, it only takes ~20 minutes ...

Note: for building spiffs image you must also have **g++** installed

**Comment by mikey60** [comment]
Thanks for your time and help.  The errors were when using Ubuntu on VMware.  I thought I would try it on the Windows Subsystem for Linux (WSL) while Ubuntu was installing on VirtualBox and it worked just fine. The only problem is that I can not flash the device because I do not have the insider version of Windows 10.  I believe the USB serial port capability will be included in the general WIndows 10 release in September or October.  I am closing the issue.

**Comment by straga** [comment]
I am use VMware virtual machine with ubuntu. Installed docker. And use all stuff in container it works very well.
