### ISSUE TITLE
ESP-NOW and high speed LEDC PWM support?

### ISSUE THREAD

**Issue by kristsm** [loboris/MicroPython_ESP32_psRAM_LoBo#30]
Hello! Thinking on going for micropython from arduino framework. Are these esp32 features available in your port? Couldn't find any info on that. Thank you!

**Comment by loboris** [comment]
[PWM](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/pwm) is fully supported.
ESP-NOW is not supported, the implementation is planned for March/April...
