### ISSUE TITLE
Proper attribution

### ISSUE THREAD

**Issue by MrSurly** [loboris/MicroPython_ESP32_psRAM_LoBo#31]
Please make sure you provide proper attribution for the code you're including here.  

One such example:

This file:
https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/esp32/machine_rtc.c

Contains substantial amounts of (`machine_rtc_wake_on_ext0` and `machine_rtc_wake_on_ext1` in their entirety) code from here:
https://github.com/MrSurly/micropython-esp32/blob/dev-deepsleep/ports/esp32/machine_rtc.c

Yet my name and copyright have been removed entirely.

**Comment by loboris** [comment]
I'm sorry, it was not intentional.
` * Copyright (c) 2017 "Eric Poulsen" <eric@zyxod.com>`
will be included with the next commit.
Thank you for pointing it out.
Please report if you find any other example.

**Comment by MrSurly** [comment]
Thank you.
