### ISSUE TITLE
os.stat('/flash') returns Errno 22

### ISSUE THREAD

**Issue by bboser** [loboris/MicroPython_ESP32_psRAM_LoBo#32]
Following code returns an error (works on the pyboard):
`
>>> import os
>>> os.stat('/flash')
OSError: [Errno 22] EINVAL
`

Other than that, os.stat appears to work correctly, e.g.
`
>>> os.listdirI()
['boot.py', 'main.py', 'lib']
>>> os.stat('boot.py')
(33279, 0, 0, 0, 0, 0, 1797, 394032, 1509659740, 394019)
`

**Comment by Avi-TelnT** [comment]
os.listdirI() has extra no need typo I

**Comment by loboris** [comment]
Fixed in latest commit, thanks for reporting.
