### ISSUE TITLE
./BUILD.sh firmware produces incorrect flash.sh

### ISSUE THREAD

**Issue by bboser** [loboris/MicroPython_ESP32_psRAM_LoBo#33]
In the newest version of the firmware build, there is a problem with target "firmware".

The Makefile in the build directory defines target "print_flash_cmd" which is called by target "firmware". The include at the end of the Makefile overrides "print_flash_cmd" (make issues a warning) with the version that does not work properly.

Possible fix:
Rename target "print_flash_cmd" to e.g. "print_flash_cmd_overwrite" in Makefile and lines 461 and 470 in BUILD.sh.

**Comment by loboris** [comment]
I've corrected it already, it will be pushed today with some other changes.

**Comment by loboris** [comment]
The corrected version is commited.
