### ISSUE TITLE
MPY-Cross

### ISSUE THREAD

**Issue by garudaonekh** [loboris/MicroPython_ESP32_psRAM_LoBo#337]
Hi,
is mpy-cross working in this build? Existing build, mpy cross not work. I rebuild but still not work.

`ValueError: incompatible .mpy file`

thanks

**Comment by curlyz** [comment]
I have been here before, some of the first bytes of mpy file tell which version of micropython and which version of idf build, it must match to be able to run on the burned firmware. Luckily, you only need to **try to download all compiled mpy from pypi and try each of them.** , check the release history

**Comment by garudaonekh** [comment]
Thanks. Actually, I run mpy-cross using another version for my other board. 
After I rebuild this whole project, mpy-cross work.

Thanks;
