### ISSUE TITLE
OSError: RTC instance already created, only one can be used.

### ISSUE THREAD

**Issue by slzatz** [loboris/MicroPython_ESP32_psRAM_LoBo#34]
Latest version of software on ESP32 without psRAM

After a soft and hard reboot, this line in a script:

    rtc = machine.RTC()

results in:

    OSError: RTC instance already created, only one can be used.

**Comment by loboris** [comment]
Thank you for informing about this and sorry for the bug.

It is fixed now and changes commited to the repository.

**Comment by slzatz** [comment]
Thanks for the quick fix
