### ISSUE TITLE
Documentation : compile

### ISSUE THREAD

**Issue by Liberasys** [loboris/MicroPython_ESP32_psRAM_LoBo#36]
For information with Debian 9 I had to install those packages :
libncurses5-dev
flex
bison
gperf

**Comment by loboris** [comment]
Info about Prerequisites is added to the [Wiki](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/build).

Does Debian 9 have the `libncurses-dev` packages or `libncurses5-dev` must be explicitly installed ?

**Comment by Liberasys** [comment]
It seems to work too with libncurses-dev :-)
