### ISSUE TITLE
It seems that microWebSrv failed to compile. 

### ISSUE THREAD

**Issue by Avi-TelnT** [loboris/MicroPython_ESP32_psRAM_LoBo#37]
It seems that microWebSrv failed to compile. 
Can you offer how to check the inner web server at /flash/www directory? 

avi@avi-virtualbox:~/esp/MicroPython/MicroPython_BUILD$ mf
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
/home/avi/esp/MicroPython/MicroPython_BUILD/components/micropython/py/mkenv.mk:63: warning: undefined variable 'HOST_PLATFORM'
/home/avi/esp/esp-idf/make/component_wrapper.mk:179: warning: overriding recipe for target 'libmicropython.a'
/home/avi/esp/MicroPython/MicroPython_BUILD/components/micropython/py/mkrules.mk:132: warning: ignoring old recipe for target 'libmicropython.a'
/home/avi/esp/MicroPython/MicroPython_BUILD/components/micropython/py/mkrules.mk:113: warning: undefined variable 'MPY_CROSS_FLAGS'
MPY /home/avi/esp/MicroPython/MicroPython_BUILD/components/micropython/esp32/modules/microWebSrv.py
make[1]: /home/avi/esp/MicroPython/MicroPython_BUILD/components/micropython/mpy-cross/mpy-cross: Command not found
/home/avi/esp/MicroPython/MicroPython_BUILD/components/micropython/py/mkrules.mk:113: recipe for target '/home/avi/esp/MicroPython/MicroPython_BUILD/build/frozen_mpy/microWebSrv.mpy' failed
make[1]: *** [/home/avi/esp/MicroPython/MicroPython_BUILD/build/frozen_mpy/microWebSrv.mpy] Error 127
/home/avi/esp/esp-idf/make/project.mk:428: recipe for target 'component-micropython-build' failed
make: *** [component-micropython-build] Error 2

**Comment by loboris** [comment]
microWebSrv compiles and run without problem.

How are you building your firmware, what is **mf** command (`avi@avi-virtualbox:~/esp/MicroPython/MicroPython_BUILD$ mf`)
You should build using **BUILD.sh** script.

**Comment by Avi-TelnT** [comment]
mf is an alias for ./BUILD.sh flash 
And yesterday, it does build after I run ./BUILD.sh clean
Since I have no problem to send a command ./BUILD.sh clean after new update of your code, all is OK
Thank you for your effort and support.

**Comment by Avi-TelnT** [comment]
How you embedded a photo in this forms?

**Comment by loboris** [comment]
It is embeded in  _components/micropython/esp32/modules_examples/webserver/www/index.html_
www directory has to be placed into the the root of your MicroPython file system.
