### ISSUE TITLE
ftp server pwd and cwd commands don't work

### ISSUE THREAD

**Issue by mkarliner** [loboris/MicroPython_ESP32_psRAM_LoBo#38]
And assuming I have the right code, I can see why. local cwd is not set for the pwd and I think it should be os.listdir rather than uos. 

`elif command == "PWD":
                        cl.sendall('257 "{}"\r\n'.format(cwd))
                    elif command == "CWD":
                        try:
                            files = uos.listdir(path)
                            cwd = path
                            cl.sendall(msg_250_OK)
                        except:
                            cl.sendall(msg_550_fail)`

Tested by using the ftp CLI on OSX.

**Comment by loboris** [comment]
uftpserver is now updated.
Could you test again and report the issues, I haven't tested it on OSX.
BTW, uos and os are the same module.

**Comment by mkarliner** [comment]
Bug is still present after git pull, ./BUILD.sh clean, ./BUILD.sh, ./BUILD.sh flash


ON OSX

bigmac:MicroPython_BUILD mike$ ftp 192.168.10.169
Connected to 192.168.10.169.
220 Micropython FTP Server
Name (192.168.10.169:mike): micro
331
Password:
230
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> pwd
Unable to determine remote directory
ftp>

ON Raspberry Pi (Raspbian)

pi@raspberrypi:~ $ ftp -p 192.168.10.169
Connected to 192.168.10.169.
220 Micropython FTP Server
Name (192.168.10.169:pi): micro
331
Password:
230
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> pwd
257 /
ftp> cwd
?Invalid command
ftp> ls
227 (192,168,10,169,7,232)
150
drw-rw-r--   1 root  root         0 Jan 01 1970 flash
226
ftp>

This does not surprise me, as looking at the last update, the code for these commands has not changed.

Why does this matter? Because various ftp sync mechanisms use these commands

**Comment by loboris** [comment]
On Raspbery Pi you are starting the ftp client in **passive** mode (`ftp -p 192.168.10.169`).
You may try to use explicit passive mode option (**-p**) on OSX too, even though on Mac OS ftp client should try to use passive mode by default.
The pwd response from ftp server is `257` `PATH`. As `PATH` is returned over data channel, it will not work in active mode.

There are no `cwd` command in ftp client. Use `cd` to change remote working directory.

**Comment by mkarliner** [comment]
To be clear, pwd on RPi with active mode does not work, with passive mode it does.
pwd on OSX does not work, in either mode. I think it's a fairly basic command to be working.
I realise that it may well be an OSX bug, however, that is not a given, as OSX has had ftp for many years, and I've personally used it with micropython and other ftp servers.

**Comment by loboris** [comment]
I've tested the ftp on Mac High Sierra (had to instal inetutils with brew).
Tested in passive mode with debug option:

```
Boriss-iMac:~ boris$ ftp -p -d 192.168.0.16
Connected to 192.168.0.16.
220 Micropython FTP Server
Name (192.168.0.16:boris): micro
---> USER micro
331 
Password: 
---> PASS XXXX
230 
ftp> ls
---> PASV
227 (192,168,0,16,7,232)
---> LIST
150 
drw-rw-r--   1 root  root         0 Jan 29 2018 flash
226 
ftp> pwd
---> PWD
257 /
ftp> cd flash
---> CWD flash
250 
ftp> pwd
---> PWD
257 /flash/
ftp> ls
---> PASV
227 (192,168,0,16,7,232)
---> LIST
150 
-rw-rw-r--   1 root  root       113 Jan 01 1970 boot.py
226 
ftp> disconnect
---> QUIT
221 
ftp> quit
Boriss-iMac:~ boris$ 
```

There was a bug in ftp server preventing the connection on clients which issues `FEAT` command before login. It is fixed now and the update will be committed tomorrow.
