### ISSUE TITLE
utime.ticks_diff(): Overflow error 

### ISSUE THREAD

**Issue by robert-hh** [loboris/MicroPython_ESP32_psRAM_LoBo#4]
ticks_diff() raises an overflow error, if its arguments are >= 2**31 (2147483648). utime.ticks_us() and utime.ticks_ms() may return such values. As long as these values do not overflow, which takes a while with 64 bit values, the need for ticks_diff() is questionable, since it simply calculates the difference.

**Comment by robert-hh** [comment]
I had in mind that you changed ticks_xx to return 64 bit values, which seems not to be in the code. The actual behavior is stable.

**Comment by loboris** [comment]
There were som bugs in ticks_xx implementation, It is fixed now and will be pushed with the next update (later today or tomorrow).

**Comment by robert-hh** [comment]
OK & Thanks.
