### ISSUE TITLE
mDNS Module wiki example with an error

### ISSUE THREAD

**Issue by djairjr** [loboris/MicroPython_ESP32_psRAM_LoBo#42]
Where it reads:
_ = mdns.addService('_http', '_tcp', 80, "MicroPython", {"board": "ESP32", "service": "mPy Web server"))

should be:
_ = mdns.addService('_http', '_tcp', 80, "MicroPython", {"board": "ESP32", "service": "mPy Web server"}) #replace the parentheses with braces

**Comment by loboris** [comment]
Thanks, corrected.
