### ISSUE TITLE
mDNS Example - start method needed

### ISSUE THREAD

**Issue by djairjr** [loboris/MicroPython_ESP32_psRAM_LoBo#43]
mdns = network.mDNS()
    mdns.start ("ESP32Dev", "ESP32") #<<< Needed, or else I got an error.
    _ = mdns.addService('_ftp', '_tcp', 21, "ESP32Dev", {"board": "ESP32", "service":  "FTP File transfer", "passive": "True"})
    _ = mdns.addService('_telnet', '_tcp', 23, "ESP32Dev", {"board": "ESP32", "service": "Telnet REPL"})
    _ = mdns.addService('_http', '_tcp', 80, "ESP32Dev", {"board": "ESP32", "service": "Servidor Web"})

**Comment by loboris** [comment]
Thanks again, I hope everything is ok now.
