### ISSUE TITLE
I2C Slave

### ISSUE THREAD

**Issue by diginfo** [loboris/MicroPython_ESP32_psRAM_LoBo#43]
> Re: I2C slave?
> I2C slave is supported in esp-idf.
> I'm planning to add hardware I2C slave support in my Micropython port the next month.

https://forum.micropython.org/search.php?st=0&sk=t&sd=d&sr=posts&keywords=i2c+slave

Just wondering whether this is in the pipeline ?

**Comment by Avi-TelnT** [comment]
Hi @diginfo
I2C slave referring that will be other MCU that will read information from ESP32 over I2C and to other MCUs on the same I2C bus. 
The question is why?  ESP32 has 3 UARTs that can do that full duplex. Easy... 
ESP32 is the main MCU, why you need another MCU? 
Can you describe a real-life use case that needs that? 
Normal ESP32 I2C uses as a master to read sensors hook on the same I2C.

**Comment by diginfo** [comment]
I want to create a I2C slave device using ESP32 micropython that can be read from a master, and loboris mentioned in a post that this was a feature he was gong to add last month ?!

**Comment by Avi-TelnT** [comment]
ESP32 as a master exists in the current firmware.

**Comment by Avi-TelnT** [comment]
See demo....
import machine
pin12 = machine.Pin(12, machine.Pin.OUT)
pin12.value(1)
pin13 = machine.Pin(13, machine.Pin.IN, machine.Pin.PULL_UP)
print(pin13.value())
i2c = machine.I2C(scl=machine.Pin(21), sda=machine.Pin(22))
i2c.scan()
addr=0xAA
i2c.writeto(addr, b'1234')
i2c.readfrom(addr, 4)

**Comment by diginfo** [comment]
Thanks, yes I know the master exists, I need to use esp as a SLAVE device not a master.

**Comment by Avi-TelnT** [comment]
Can you describe a real-life use case that needs that?

**Comment by diginfo** [comment]
Yes, talking to a I2C master device that is not designed by you and not under your control.

In my case, I am replacing an item that is now obsolete, I have already done this using PIC micro-controller, but would like to do it with ESP32.

Not really sure why you're asking this as I2C slave is quite a common requirement for micro-controllers and the PYBOARD already supports this https://docs.micropython.org/en/latest/pyboard/library/pyb.I2C.html#pyb-i2c

**Comment by diginfo** [comment]
Never mind, I am closing this.

**Comment by Avi-TelnT** [comment]
I belive you need ESP32 master to read sensor data, as I2C slave. 
See the demo on the URL you provide. 
The slave is the sensoe I2C address, been reads by ESP32 master side. 
i2c = I2C(1)                         # create on bus 1
i2c = I2C(1, I2C.MASTER)             # create and init as a master
i2c.init(I2C.MASTER, baudrate=20000) # init as a master
i2c.init(I2C.SLAVE, addr=0x42)       # init as a slave with given address
i2c.deinit()                         # turn off the peripheral

**Comment by tuupola** [comment]
Real life use case is to make ESP32+Micropython based i2c device.

**Comment by Avi-TelnT** [comment]
I2C has too sides. 
The prosessor side, and sensors side. 
The prosessor, ESP must be I2C master profile
The sensors side, must be I2C slave profile. 
So onlt ESP32 as muster can read data from sensors. 
Sensors can be master, sice it does not have prosessing power. 
And ESP32+Micropython based has i2c  as master. 
I do not see any use of ESP32 as a slave. Since if you like to read from ESP32 by other prosessoer, yu can do that better and faster using UART. I2C is slow and not full suplex.

**Comment by tuupola** [comment]
I do know how I2C works.

**Comment by diginfo** [comment]
@tuupola - I gave up on this and closed the issue, it seems that @Avi-TelnT is unable to understand why anyone would ever need to create a i2c slave.

@Avi-TelnT I do not want the ESP32 to act as a master at all, I just want it to behave as a slave, nothing else.

I am creating a sensor that other devices **that are not designed by** me will talk to, it will **ONLY ACT AS A SLAVE**.

I have never said that I want the ESP32 to act as both a master and a slave, I know how I2C works, have been using it for over 20 years on various devices. !

**Comment by tuupola** [comment]
As a sidenote, since ESP32 has two hardware I2C buses it actually can simultaneously act as both slave and master. It can even read from itself. Not too useful but still possible. I did some [dummy test](https://github.com/tinkermetry/firmware-esp32) about this which is based on Expressif [i2c example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2c).
