### ISSUE TITLE
Can't use import gsm

### ISSUE THREAD

**Issue by djairjr** [loboris/MicroPython_ESP32_psRAM_LoBo#49]
Boris,

Can't use GSM with MicroPython ESP32_LoBo_v3.1.14 - 2017-01-29 on ESP32 board with ESP32
>>> import gsm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'gsm'

What is wrong?
I've flashed my ESP32Dev with esp32_all firmware.

Thanks again!

Djair

**Comment by loboris** [comment]
GSM module is not enabled by default.
You must enable it via **menuconfig**:
`→ MicroPython → Modules → Use GSM module`
and build the firmware.

I'll enable it in `*_all_*` firmwares on next commit.

**Comment by djairjr** [comment]
Ok. Build it and working! Thanks!
