### ISSUE TITLE
Documentation: Only baseline JPG files supported

### ISSUE THREAD

**Issue by tuupola** [loboris/MicroPython_ESP32_psRAM_LoBo#51]
[Documentation](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/display#tftimagex-y-file-scale-type) for  `tft.image()` should mention that only baseline JPG images are supported. Progressive and lossless formats are not supported.

**Comment by loboris** [comment]
Thanks.
I've added the info on both JPG and BMP format linitations.

**Comment by tuupola** [comment]
Thanks!

**Comment by callimero** [comment]
I could not get a BMP to work. Tried Gimp and Paint.

![Gimp_PNG](https://user-images.githubusercontent.com/7713008/190584698-85a4df23-1f1c-42df-bb44-a739e85c144a.png)
