### ISSUE TITLE
telnet?

### ISSUE THREAD

**Issue by VR-AntHill** [loboris/MicroPython_ESP32_psRAM_LoBo#53]
Hi there - got wifi network up and running, and managed to start up FTP and connect w/FZ - nice nice nice!
tried telnet - no dice

>>> network.telnet.start(user="micro",password="python", timeout=300)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'telnet'

help!

**Comment by brandond** [comment]
Did you enable telnet in menuconfig?

**Comment by VR-AntHill** [comment]
duh!
I must have been really tired last night - I swear I searched for it in menuconfig. 
Yup, enabled, recompiled, up and running

thanks, and sorry for the bandwidth...
