### ISSUE TITLE
utime.ticks_diff() and ticks_add(): Overflow error

### ISSUE THREAD

**Issue by robert-hh** [loboris/MicroPython_ESP32_psRAM_LoBo#54]
Since both ticks_us() and ticks_ms() may return integers longer than 31 bit, ticks_diff() and ticks_add() should be able to deal with that. But they cannot. Try:
`ticks_diff(0x80000000, 0x80000001)`
or
`ticks_add(0x80000000, 1)`

(sysname='esp32', nodename='esp32', release='3.1.11', version='ESP32_LoBo_v3.1.11 on 2017-01-24', machine='ESP32 board with ESP32')

**Comment by loboris** [comment]
Thanks for reporting this.
I have fixed it, the update will be commited later today.

**Comment by loboris** [comment]
Update is now committed.

**Comment by kevinkk525** [comment]
This works for me.
```
>>> time.ticks_diff(0x80000000, 0x80000001)
-1
>>> time.ticks_diff(0x80000000, 1)
2147483647
```
