### ISSUE TITLE
genconfig make all failed

### ISSUE THREAD

**Issue by xwct** [loboris/MicroPython_ESP32_psRAM_LoBo#6]
build fails following your instructions on os x 10.11.6

```
Building MicroPython for ESP32 with esp-idf master branch

================================
Building MicroPython firmware...
================================
GENCONFIG
/bin/sh: /Users/ole/build/MicroPython_ESP32_psRAM_LoBo/esp-idf/tools/kconfig/conf: cannot execute binary file
make: * No rule to make target `/Users/ole/build/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/build/include/config/auto.conf', needed by `/Users/ole/build/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/build/bootloader/bootloader.bin'.  Stop.
'make all' FAILED!
```

**Comment by loboris** [comment]
I've tested the build on MacOS Sierra and it passes.
Included toolchain is built for Linux, so you have to download espressif toolchain for MacOS, check
[Set up of Toolchain for Mac OS](https://esp-idf.readthedocs.io/en/v2.0/macos-setup.html) for instructions.
There is also some problems with included esp-idf, so please clone esp-idf v2.1 repository an use it.
Edit your BUILD.sh and change exports for esp-idf and toolchain.
There is also small bug in **MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/extmod/vfs_native.c** The line 55 has semicolon at the end, it compiles without error on Linux but fails on MacOS.
I'll push the corrected one soon, for now you can edit it manualy.

You have also to delete the **MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/mpy-cross/mpy-cros** which is also built for linux. If not found, BUILD.sh will compile the new one, this time for MacOS.

If you want to build with psRAM support, you must [Compile the toolchain from source using crosstool-NG](https://esp-idf.readthedocs.io/en/v2.0/macos-setup.html#alternative-step-1-compile-the-toolchain-from-source-using-crosstool-ng).
I'll build the toolchain for MacOS later this week and include it in the repository.

**Comment by MrBuddyCasino** [comment]
Just tried building for the first time on OSX, thankfully I've found this issue. Will wait until OSX support is integrated. Thanks for this project!

**Comment by loboris** [comment]
**Building on MacOS** is now fully supported, all needed toolchains are included.
**BUILD.sh** detects the OS and unpacks the right toolchains for it.
Tested on MacOS Sierra.
