### ISSUE TITLE
Small error in documentation

### ISSUE THREAD

**Issue by Wessix** [loboris/MicroPython_ESP32_psRAM_LoBo#60]
In the documentation "network.ftp.start([user="micro",password="python",buffsize=1024,timeout=300])" is written.
This throws an error for me. Without the "[" and the "]" it works.

**Comment by carterw** [comment]
Same problem with the telnet server documentation.

**Comment by loboris** [comment]
Putting arguments in square brackets in documentation means they are **optional**.
It is a [common syntax rule](https://stackoverflow.com/questions/38209396/what-do-the-square-brackets-around-parameters-mean-in-the-official-documentation)

**Comment by Wessix** [comment]
Ok thx for the clarification
