### ISSUE TITLE
Non-blocking quickmail build error.

### ISSUE THREAD

**Issue by mfp20** [loboris/MicroPython_ESP32_psRAM_LoBo#66]
What about this one?

``
In file included from components/micropython/./py/obj.h:31:0,
                 from components/micropython/./py/mpstate.h:35,
                 from components/micropython/./py/mpthread.h:53,
                 from components/quickmail/./quickmail.c:29:
components/micropython/./py/qstr.h:42:39: fatal error: genhdr/qstrdefs.generated.h: No such file or directory
compilation terminated.
``

**Comment by loboris** [comment]
Could you give more detailes about under what circumstances this error occured?
What should "Non-blocking" error mean?
Try to run `./BUILD.sh clean all`.

**Comment by loboris** [comment]
Libquickmail is now removed.
