### ISSUE TITLE
Usage of machine.Neopixel

### ISSUE THREAD

**Issue by icb-** [loboris/MicroPython_ESP32_psRAM_LoBo#8]
It looks like `machine.Neopixel` is incomplete, and I'm not finding any documentation on its usage.
I've mostly been able to gather how to use it from reading the code, but I have a few questions.

- [ ] What is `type` on the constructor? It doesn't appear to be used. I assume it's intended to specify pre-determined sets of color order and bytes per pixel? I don't see any way to specify 3 bytes-per-pixel for RGB (not RGBW) pixels.

- [ ] Likewise, `color_order` appears to only be able to set all 4 colors.

- [ ] `rmtchan` is in the constructor, but later you force the channel to `RMT_CHANNEL_0`.

My LEDs haven't arrived yet, so I can't test any of this in the real world.

**Comment by loboris** [comment]
I have plans to upgrade the driver with more options, that is the reason why there are some inconsistencies. RGBW support is planned, but not used for now, as well as 4 char color order.
RMT channel is fixed to 0, I'm planning to include the RMT module and some other drivers also uses the RMT peripheral (DHT, 1-wire (soon)). _rmtchan_ will be mandatory (with default value of 0) and checked if used by other driver.
The driver in the current state works fine, but it uses a lot of memory and is not suitable for more than 50 pixels (if not using psRAM). I'm testing a slightly different approach which will enable using unlimited number of pixels...
The documentation for this, as well as other modules will be ready soon (probably at the end of this week or early next week)
