### ISSUE TITLE
Programmation with esptool

### ISSUE THREAD

**Issue by GregCle** [loboris/MicroPython_ESP32_psRAM_LoBo#83]
Hi,

I made a python code that uses Loboris tools to program the ESP32.

Example code:
```
command_Erase = './BUILD.sh erase'
command_flash = './BUILD.sh -v flash'
command_makefs = './BUILD.sh makefs'
command_flashfs = './BUILD.sh flashfs'

[...]

os.system ('echo% s | sudo -S% s'% (sudoPassword, command_Erase))
os.system ('echo% s | sudo -S% s'% (sudoPassword, command_flash))

[...]
```

It works super well.

I wanted simplify the programming of ESP32 using esptool. I do not know why, but after erase the memory, I'm not able to program it.

The same thing happens if I program it, I'm not able to erase it anymore.

I can do one action, but not two.

example code:
```
command_Erase = 'esptool.py erase_flash'
command = 'esptool.py --chip esp32 --port / dev / ttyUSB0 --baud 921600 --before default_reset --after no_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 / home / bootloader. bin '

os.system (command_Erase)
os.system (command)
```

I did not find in Loboris's code if there was a difference in its command erase and program.

I noticed in Loboris code, after erase, he stay in the booltoader, but not with esptool. How to stay in the bootloader?

Thanks

**Comment by loboris** [comment]
You should configure in menuconfig:
`→ Serial flasher config → After flashing (Stay in bootloader)`

**Comment by loboris** [comment]
I'll close the issue, please reopen if needed.
