### ISSUE TITLE
sftp possible for secure remote sdcard access?

### ISSUE THREAD

**Issue by Ian-Re** [loboris/MicroPython_ESP32_psRAM_LoBo#85]
Hi boris,

Just want to say I'm a few days into this python port and its amazing! I've got a ftp running to retrieve data from a remote sdcard connected to the esp32. Its not on my local network and I want to retrieve this to my pc, not a server. Is there any way that I could implement a sftp that would work with the FileZilla client?

I'd really appreciate any help

**Thank in advance!**

**Comment by loboris** [comment]
SFTP/SCP **client** is implemented in the **ssh** module.

SSH **server** is not yet implemented, I have some plans for it, but it is not planned for the next couple of months.
