### ISSUE TITLE
build errors from fresh clone

### ISSUE THREAD

**Issue by carterw** [loboris/MicroPython_ESP32_psRAM_LoBo#87]
Performed a fresh clone, went into build menu and turned off telnet and FTP here;
menu->MicroPython->System settings

./BUILD.sh all -v

/micropython/py/modthread.c: In function 'mod_thread_list':
/micropython/py/modthread.c:450:24: error: 'TELNET_STACK_LEN' undeclared (first use in this function)
      TelnetTaskHandle, TELNET_STACK_LEN, TELNET_STACK_LEN - uxTaskGetStackHighW/micropython/py/modthread.c:454:21: error: 'FTP_STACK_LEN' undeclared (first use in this function)
      FtpTaskHandle, FTP_STACK_LEN, FTP_STACK_LEN - uxTaskGetStackHighWaterMark(

Turned telnet and FTP back on, ran clean and rebuilt successfully.

**Comment by ldecicco** [comment]
I confirm the issue.

**Comment by loboris** [comment]
Thanks for reporting this.
The fix is commited and building without telnet and/or ftp server enabled works.

**Comment by carterw** [comment]
Seems to be working now, thanks.
