### ISSUE TITLE
The SPI hw code errors when cs is not set.

### ISSUE THREAD

**Issue by MZachmann** [loboris/MicroPython_ESP32_psRAM_LoBo#89]
Probably benign but annoying, when you init SPI without cs it prints error messages.

I added an if(cs != -1) before line 110 of machine_hw_spi.c to check for -1 and not set the gpio stuff and it cleared up.

**Comment by loboris** [comment]
Thank you for reporting. I'll fix it.

**Comment by loboris** [comment]
It is fixed inn the latest commit.
