### ISSUE TITLE
os.listdir() BUG

### ISSUE THREAD

**Issue by 0x1abin** [loboris/MicroPython_ESP32_psRAM_LoBo#9]
```bash
>>> os.listdir()
['boot.py', 'lib', 'file1.py']
>>> os.listdir('lib')
['file2.py', 'dir1/file2.py', 'dir1/file1.py', 'dir1/dir2', 'dir1/dir2/file3.py', 'dir1/dir3', 'dir1']
>>> os.listdir('lib/dir1')
['file2.py', 'file1.py', 'dir2', 'dir2/file3.py', 'dir3']
>>> 
```

**Comment by ghost** [comment]
Noticed that, too. Oddly does not occur in '.'.

**Comment by loboris** [comment]
**spiffs file system** now uses the (modified) esp-idf **spiffs** driver, which can be configured via menuconfig:
`→ Component config → SPIFFS Configuration`
It looks like you have disabled the `Enable directories` option.

You can try to erase the flash with `./BUILD erase`, then flash the firmware.
The filesystem will be formated, and directories should work as expected.

**Comment by ghost** [comment]
Just checked - Enable directories is checked:



Is there some other configuration option for this?

Thanks,
Bernhard

**Comment by loboris** [comment]
Thank you for reporting this.

It was my fault, I've forgot to include some modifications to esp-idf spiffs driver needed to correctly list the directories.
The update is just commited, please pull the changes, `os.listdir()` now works as it should with subdirectories.
