### ISSUE TITLE
esp32-wrover-v4 support ?

### ISSUE THREAD

**Issue by straga** [loboris/MicroPython_ESP32_psRAM_LoBo#9]
ref link: [esp32-wrover-v4](http://esp32.net/images/Espressif/ESP32-WROVER/)
build with psram.

but uPY  heap size = 94208 bytes, what need else configure?
```
I (2323) boot: segment 8: paddr=0x001538e8 vaddr=0x50000000 size=0x00400 (  1024) load
I (2352) cpu_start: PSRAM mode: flash 40m sram 40m
I (2366) cpu_start: PSRAM initialized, cache is in even/odd (2-core) mode.
I (2390) cpu_start: Pro cpu up.
I (2401) cpu_start: Starting app cpu, entry point is 0x400811d4
0x400811d4: call_start_cpu1 at /esp32/MicroPython_ESP32_psRAM_LoBo/esp-idf_psram/components/esp32/./cpu_start.c:217

I (0) cpu_start: App cpu up.
I (5095) heap_alloc_caps: SPI SRAM memory test OK
I (5096) heap_alloc_caps: Initializing. RAM available for dynamic allocation:
I (5101) heap_alloc_caps: At 3F800000 len 00400000 (4096 KiB): SPIRAM
I (5123) heap_alloc_caps: At 3FFAE2A0 len 00001D60 (7 KiB): DRAM
I (5144) heap_alloc_caps: At 3FFC0F10 len 0001F0F0 (124 KiB): DRAM
I (5165) heap_alloc_caps: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (5186) heap_alloc_caps: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (5208) heap_alloc_caps: At 400997D0 len 00006830 (26 KiB): IRAM
I (5229) cpu_start: Pro cpu start user code
I (5291) cpu_start: Starting scheduler on PRO CPU.
I (2875) cpu_start: Starting scheduler on APP CPU.

FreeRTOS running on BOTH CORES, MicroPython task started on App Core.

uPY stack size = 15360 bytes
uPY  heap size = 94208 bytes
```

**Comment by loboris** [comment]
Run _BUILD.sh menuconfig psram_ and check under MicroPython menu the heap size.
If you have problems, just delete **sdkconfig**, **sdkconfig.old** and **build** directory. Then you can run _BUILD.sh menuconfig psram_ again, enable psram and check the MicroPython heap size, the default one for psram build should be selected, which is 2MB.
I would also recommend to build with psram support in unicore mode (FreeRTOS running only on the first core) until psram support is fully included into esp-idf master branch.

**Comment by straga** [comment]
Thanks after delete sdkconfig, sdkconfig.old and unicore mode. Now it works. 

FreeRTOS running only on FIRST CORE.

uPY stack size = 31744 bytes
uPY  heap size = 2097152 bytes (in SPIRAM using pvPortMallocCaps)

**Comment by MartyMacGyver** [comment]
Doc updates related to this bug:

For `./BUILD.sh menuconfig psram`, is that `psram` part a specific command line option required to make psram work? If so, that should be documented.

The heap size with psram appears to default to 512 (KB). I am manually changing it to 2048 (KB) which == 2MB.

For unicore operation, `Component config → FreeRTOS → Run FreeRTOS only on first core` is selected.

**Comment by loboris** [comment]
@MartyMacGyver
`psram` parameter in no longer used in **BUILD.sh**.
psRAM support is compiled if `→ Component config → ESP32-specific → Support for external, SPI-connected RAM` is selected in **menuconfig**.
See [the documentation](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/build)

**Comment by MartyMacGyver** [comment]
I assume that is a recent change as your previous comment above recommended it, which led me to ask.
