### ISSUE TITLE
Documentation: How is the TFT foreground color set?

### ISSUE THREAD

**Issue by stroobandt** [loboris/MicroPython_ESP32_psRAM_LoBo#94]
At several instances in the ![`display.TFT()` documentation](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/display#tfttextx-y-text--color) one reads:

> If `color` is not given, current foreground color is used.

My question is rather simple: How does one go about setting the TFT foreground colour?

**Comment by loboris** [comment]
The latest commit added `tft.get_bg()`, `tft.get_fg()`, `tft.set_bg(color)` and `tft.set_fg(color)` methods.
