### ISSUE TITLE
Extend ASCII with ISO/IEC 8859-15 for TFT & OLED Fonts

### ISSUE THREAD

**Issue by stroobandt** [loboris/MicroPython_ESP32_psRAM_LoBo#95]
Both TFT & OLED fonts provided by LoBo MicroPython currently only cover the basic ASCII character set.
These 95 printable characters are sufficient for English graphic user interfaces.

However, in some circumstances, one might be legally required to provide a graphic user interface in the language of the user. As it currently stands, it is nearly impossible to write any intelligible text on the screen in languages that heavily rely upon accented characters; French being a nice example of this.
This poses a serious problem for the pan-European adoption of LoBo MicroPython.

Hence, my call for extending the ASCII of both the TFT and OLED fonts.
In this respect, code page ISO/IEC 8859-15 probably makes the most sense, as it covers the highest number of languages.

>Perhaps the most widely used part of ISO/IEC 8859, covering most Western European languages: Danish (partial), Dutch (partial), English, Faeroese, Finnish (partial), French (partial), German, Icelandic, Irish, Italian, Norwegian, Portuguese, Rhaeto-Romanic, Scottish Gaelic, Spanish, Catalan, and Swedish. Languages from other parts of the world are also covered, including: Eastern European Albanian, Southeast Asian Indonesian, as well as the African languages Afrikaans and Swahili. The missing euro sign and capital Ÿ are in the revised version ISO/IEC 8859-15.
> 
> ISO/IEC 8859-15 is a revision of 8859-1 that removes some little-used symbols, replacing them with the euro sign € and the letters Š, š, Ž, ž, Œ, œ, and Ÿ, which completes the coverage of French, Finnish and Estonian.

**Comment by stroobandt** [comment]
Actually, all my problems would be instantly resolved if `DejaVuSans24.c` had **_by default_** extended ASCII up to character 255.
Those could come from either code page ISO/IEC 8859-15 —or even ISO/IEC 8859-16 if you prefer that «in your neck of the woods,» Boris.

**Comment by stroobandt** [comment]
The following font converter might prove useful:
https://littlevgl.com/font-converter

**Comment by loboris** [comment]
I'm working on implementing the fonts for extended ASCII and differen code pages, but as it is not a priority, it will be ready before summer.
I'll close the issue, please reopen if needed.

The [forum](https://loboris.eu/forum/) may be better place to discuss the feature requests.
