### ISSUE TITLE
Typo in ...esp32/modnetwork.c

### ISSUE THREAD

**Issue by BluSpanner** [loboris/MicroPython_ESP32_psRAM_LoBo#99]
Attempting to start ftp, without stating WiFi (deliberately) results in the following error

`E (80526) [Ftp]: Invalif WiFi mode`

There's a typo in file MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/esp32/modnetwork.c

replace `Invalif` with `Invalid`

**Comment by loboris** [comment]
Thanx, I've fixed, will be commited with the next update
